import {
  Calculator,
  Radar,
  FileText,
  Hammer,
  ShieldCheck,
  DollarSign,
  Users,
  Home,
  Wrench,
  Layers,
  Leaf,
  Droplets,
  Sun,
  Ruler,
  LayoutGrid,
  PaintRoller,
  Clock,
  HardHat,
  Trash2,
  Search,
  MessageSquare,
  BadgeCheck,
  MapPin,
  Star,
  Percent,
  Wallet,
  Calendar,
  TrendingUp,
  Heart,
  GraduationCap,
  Camera,
  Truck,
  CloudRain,
  Wind,
  Snowflake,
  Thermometer,
  Zap,
  Film,
  Eye,
  List,
  Gift,
  MoreHorizontal,
  Crown,
  Gem,
  KeyRound,
  Briefcase,
  UserPlus,
  Share2,
  Landmark,
  Building2,
  Umbrella,
  Cone,
  Plus,
  Settings,
  TriangleAlert,
  User,
  Cookie,
  Link2,
  SquarePen,
  Handshake,
  Scale,
  CircleCheck,
  Megaphone,
  HandCoins,
  Lock,
  Info,
  Bell,
  RefreshCcw,
  BookOpen,
  Upload,
  CircleHelp,
  BedDouble,
  Bath,
  Folder,
  Download,
  Phone,
  LogOut,
  Video,
  Send,
  Paperclip,
  Ban,
  Monitor,
  Moon,
  Box,
  LayoutDashboard,
  Globe,
  Mail,
  type LucideProps,
} from "lucide-react";

const MAP = {
  calculator: Calculator,
  drone: Radar,
  radar: Radar,
  document: FileText,
  file: FileText,
  hammer: Hammer,
  shield: ShieldCheck,
  dollar: DollarSign,
  users: Users,
  home: Home,
  wrench: Wrench,
  layers: Layers,
  leaf: Leaf,
  droplet: Droplets,
  sun: Sun,
  ruler: Ruler,
  grid: LayoutGrid,
  brush: PaintRoller,
  clock: Clock,
  hardhat: HardHat,
  trash: Trash2,
  search: Search,
  message: MessageSquare,
  badge: BadgeCheck,
  mappin: MapPin,
  star: Star,
  percent: Percent,
  wallet: Wallet,
  calendar: Calendar,
  chart: TrendingUp,
  heart: Heart,
  graduation: GraduationCap,
  camera: Camera,
  truck: Truck,
  cloud: CloudRain,
  wind: Wind,
  snow: Snowflake,
  thermometer: Thermometer,
  zap: Zap,
  film: Film,
  eye: Eye,
  list: List,
  gift: Gift,
  more: MoreHorizontal,
  crown: Crown,
  diamond: Gem,
  key: KeyRound,
  briefcase: Briefcase,
  userplus: UserPlus,
  share: Share2,
  landmark: Landmark,
  building: Building2,
  umbrella: Umbrella,
  cone: Cone,
  plus: Plus,
  gear: Settings,
  warning: TriangleAlert,
  user: User,
  cookie: Cookie,
  link: Link2,
  edit: SquarePen,
  handshake: Handshake,
  scale: Scale,
  checkcircle: CircleCheck,
  megaphone: Megaphone,
  handcoins: HandCoins,
  lock: Lock,
  info: Info,
  bell: Bell,
  refresh: RefreshCcw,
  book: BookOpen,
  upload: Upload,
  help: CircleHelp,
  bed: BedDouble,
  bath: Bath,
  folder: Folder,
  download: Download,
  phone: Phone,
  logout: LogOut,
  video: Video,
  send: Send,
  paperclip: Paperclip,
  ban: Ban,
  monitor: Monitor,
  moon: Moon,
  box: Box,
  dashboard: LayoutDashboard,
  globe: Globe,
  mail: Mail,
  pin: MapPin,
  trend: TrendingUp,
} as const;

export type IconName = keyof typeof MAP;

export function Icon({ name, ...props }: { name: string } & LucideProps) {
  const Cmp = MAP[name as IconName] ?? Home;
  return <Cmp {...props} />;
}
