import { liveHref } from "@/lib/launch-phase";
/* Knowledge Center category pages (/learn/[category]) — mock content.
   Data-driven: add a new object + register it in KC_CATEGORY_PAGES. */

const img = (id: string) => `/images/${id}.jpg`;

export type KCArticle = { tag: string; title: string; read: string; views: string; image: string };

export type KCCategory = {
  slug: string;
  metaTitle: string;
  metaDesc: string;
  eyebrow: string;
  titleLines: string[];
  desc: string;
  image: string;
  stats: { icon: string; value: string; label: string }[];
  inThisSection: { icon: string; label: string }[];
  searchPlaceholder: string;
  tabs: string[];
  featuredHeading: string;
  featuredLabel?: string;
  featuredAccent?: boolean;
  featured: KCArticle[];
  allHeading: string;
  all: KCArticle[];
  cta: { title: string; desc: string; button: string; href: string };
  popularHeading: string;
  popular: { label: string; count: number }[];
  downloads: { title: string; size: string }[];
  trust: { icon: string; title: string; desc: string }[];
  newsletter: { title: string; desc: string; perks: string[] };
};

export const ROOF_REPLACEMENT: KCCategory = {
  slug: "roof-replacement",
  metaTitle: "Roof Replacement Guides — Knowledge Center",
  metaDesc:
    "Expert roof replacement guides for Washington homeowners — costs, materials, timelines, warranties, planning, and choosing the right contractor.",
  eyebrow: "Education Center",
  titleLines: ["Roof Replacement", "Guides"],
  desc: "Everything you need to know about roof replacement — costs, materials, timelines, warranties, planning, and choosing the right contractor.",
  image: img("1600596542815-ffad4c1539a9"),
  stats: [
    { icon: "document", value: "40+", label: "Expert Guides" },
    { icon: "calendar", value: "Updated", label: "Weekly" },
    { icon: "users", value: "15,000+", label: "Homeowners Helped" },
  ],
  inThisSection: [
    { icon: "home", label: "Replacement Basics" },
    { icon: "calendar", label: "Planning & Budgeting" },
    { icon: "layers", label: "Materials & Options" },
    { icon: "clock", label: "Process & Timeline" },
    { icon: "shield", label: "Warranties & Protection" },
    { icon: "document", label: "Hiring & Contracts" },
    { icon: "camera", label: "Real Projects & Case Studies" },
    { icon: "message", label: "FAQs" },
  ],
  searchPlaceholder: "Search roof replacement articles, guides, topics...",
  tabs: ["All Topics", "Basics", "Planning", "Materials", "Process", "Warranties", "Hiring", "Case Studies", "FAQ"],
  featuredHeading: "Featured Guides",
  featuredLabel: "Featured",
  featuredAccent: false,
  featured: [
    { tag: "Cost & Budget", title: "How Much Does a Roof Replacement Cost in Washington?", read: "12 min read", views: "45K views", image: img("1570129477492-45c003edd2be") },
    { tag: "Planning", title: "When Is the Right Time to Replace Your Roof?", read: "10 min read", views: "38K views", image: img("1632759145351-1d592919f522") },
    { tag: "Materials", title: "Best Roofing Materials for Washington Homes (2024 Guide)", read: "14 min read", views: "29K views", image: img("1576941089067-2de3c901e126") },
    { tag: "Process", title: "Step-by-Step Roof Replacement Process Explained", read: "11 min read", views: "22K views", image: img("1564013799919-ab600027ffc6") },
  ],
  allHeading: "All Guides",
  all: [
    { tag: "Planning", title: "Roof Replacement Checklist: What You Need to Know Before You Start", read: "9 min read", views: "16K views", image: img("1570129477492-45c003edd2be") },
    { tag: "Budgeting", title: "Roof Replacement Financing Options for Homeowners", read: "8 min read", views: "12K views", image: img("1531971589569-0d9370cbe1e5") },
    { tag: "Materials", title: "Architectural vs Luxury Shingles: What's the Difference?", read: "7 min read", views: "11K views", image: img("1576941089067-2de3c901e126") },
    { tag: "Planning", title: "How Long Does a Roof Replacement Take?", read: "6 min read", views: "10K views", image: img("1564013799919-ab600027ffc6") },
    { tag: "Process", title: "What to Expect on Roof Replacement Day", read: "6 min read", views: "9K views", image: img("1632759145351-1d592919f522") },
    { tag: "Warranty", title: "Understanding Roofing Warranties (Manufacturer vs Workmanship)", read: "8 min read", views: "9K views", image: img("1558036117-15d82a90b9b1") },
    { tag: "Insurance", title: "Will Insurance Pay for a New Roof? What You Need to Know", read: "10 min read", views: "8K views", image: img("1572120360610-d971b9d7767c") },
    { tag: "Case Study", title: "Full Roof Replacement in Bellevue, WA (Real Project)", read: "12 min read", views: "7K views", image: img("1600596542815-ffad4c1539a9") },
  ],
  cta: { title: "Ready to Replace Your Roof?", desc: "Get a free, no-obligation estimate in less than 60 seconds.", button: "Get Instant Estimate", href: "/estimate/instant" },
  popularHeading: "Popular Topics",
  popular: [
    { label: "Roof Replacement Cost", count: 18 },
    { label: "Best Roofing Materials", count: 14 },
    { label: "Roof Replacement Process", count: 9 },
    { label: "Warranties Explained", count: 7 },
    { label: "Signs You Need a New Roof", count: 6 },
    { label: "Insurance & Replacement", count: 5 },
    { label: "Timing & Seasons", count: 4 },
    { label: "Choosing a Contractor", count: 4 },
  ],
  downloads: [
    { title: "Roof Replacement Guide", size: "PDF · 4.2 MB" },
    { title: "Roof Replacement Checklist", size: "PDF · 1.1 MB" },
    { title: "Cost Breakdown Template", size: "PDF · 850 KB" },
    { title: "Material Comparison Chart", size: "PDF · 1.3 MB" },
  ],
  trust: [
    { icon: "chart", title: "Expert Written", desc: "All guides are written and reviewed by roofing experts with 15+ years of experience." },
    { icon: "mappin", title: "Local Focused", desc: "Content created specifically for Washington homes and climate conditions." },
    { icon: "home", title: "Real Data", desc: "Based on real project data, material performance, and field experience." },
    { icon: "calendar", title: "Always Updated", desc: "We update our content weekly to reflect the latest codes, prices, and best practices." },
  ],
  newsletter: {
    title: "Stay Ahead Of Roofing Problems.",
    desc: "Receive homeowner guides, maintenance reminders, storm alerts, seasonal tips and exclusive educational content.",
    perks: ["Expert tips & guides", "Seasonal maintenance reminders", "Storm alerts & safety tips", "New articles & videos"],
  },
};

export const ROOF_REPAIR: KCCategory = {
  slug: "roof-repair",
  metaTitle: "Roof Repair Guides — Knowledge Center",
  metaDesc:
    "Practical roof repair guides for Washington homeowners — leaks, shingles, flashing, vents, gutters, storm damage, DIY tips, and when to call a professional.",
  eyebrow: "Education Center",
  titleLines: ["Roof Repair Guides"],
  desc: "Practical guides, expert advice, and real-world solutions for every type of roof repair. Understand problems, explore solutions, and protect your home.",
  image: img("1632759145351-1d592919f522"),
  stats: [
    { icon: "document", value: "35+", label: "Expert Guides" },
    { icon: "calendar", value: "Updated", label: "Weekly" },
    { icon: "users", value: "12,000+", label: "Homeowners Helped" },
  ],
  inThisSection: [
    { icon: "home", label: "Common Roof Problems" },
    { icon: "droplet", label: "Leak Repair" },
    { icon: "layers", label: "Shingle Repair" },
    { icon: "shield", label: "Flashing Repair" },
    { icon: "wind", label: "Roof Vent Repair" },
    { icon: "droplet", label: "Gutter & Drainage Repair" },
    { icon: "cloud", label: "Storm Damage Repair" },
    { icon: "hammer", label: "DIY Tips" },
    { icon: "users", label: "When to Call a Professional" },
    { icon: "camera", label: "Real Repair Case Studies" },
    { icon: "message", label: "FAQs" },
  ],
  searchPlaceholder: "Search roof repair articles, topics, solutions...",
  tabs: ["All Topics", "Leaks", "Shingles", "Flashing", "Gutters", "Ventilation", "Storm Damage", "DIY Tips", "When to Call a Pro", "FAQs"],
  featuredHeading: "Featured Repair Guides",
  featured: [
    { tag: "Leaks", title: "How to Find and Fix a Roof Leak (Complete Guide)", read: "10 min read", views: "32K views", image: img("1564013799919-ab600027ffc6") },
    { tag: "Shingles", title: "How to Repair Missing or Damaged Shingles", read: "8 min read", views: "24K views", image: img("1570129477492-45c003edd2be") },
    { tag: "Flashing", title: "Flashing Repair: How to Stop Leaks at the Source", read: "9 min read", views: "21K views", image: img("1600585154340-be6161a56a0c") },
    { tag: "Storm Damage", title: "Storm Damage Repair: What to Do First", read: "11 min read", views: "18K views", image: img("1632759145351-1d592919f522") },
  ],
  allHeading: "All Repair Guides",
  all: [
    { tag: "Leaks", title: "Ceiling Water Stains: What They Mean and How to Fix", read: "7 min read", views: "8K views", image: img("1564013799919-ab600027ffc6") },
    { tag: "Leaks", title: "Roof Leak Repair: Step-by-Step Process", read: "9 min read", views: "16K views", image: img("1632759145351-1d592919f522") },
    { tag: "Shingles", title: "How to Seal a Roof Leak Under Shingles", read: "7 min read", views: "11K views", image: img("1570129477492-45c003edd2be") },
    { tag: "Shingles", title: "Replacing Damaged Shingles: A Homeowner's Guide", read: "8 min read", views: "9K views", image: img("1558036117-15d82a90b9b1") },
    { tag: "Flashing", title: "Chimney Flashing Repair Made Simple", read: "8 min read", views: "7K views", image: img("1576941089067-2de3c901e126") },
    { tag: "Vents", title: "How to Repair a Leaking Roof Vent", read: "6 min read", views: "6K views", image: img("1600585154340-be6161a56a0c") },
    { tag: "Gutters", title: "Fixing Leaky Gutters and Poor Drainage", read: "6 min read", views: "5K views", image: img("1605276374104-dee2a0ed3cd6") },
    { tag: "Storm Damage", title: "How to Repair Wind and Hail Damage", read: "10 min read", views: "12K views", image: img("1572120360610-d971b9d7767c") },
    { tag: "DIY Tips", title: "DIY Roof Repair: What You Can (and Can't) Do", read: "6 min read", views: "7K views", image: img("1531971589569-0d9370cbe1e5") },
    { tag: "Sealants", title: "Best Roof Sealants for Long-Lasting Repairs", read: "7 min read", views: "6K views", image: img("1583608205776-bfd35f0d9f83") },
    { tag: "Roof Maintenance", title: "Prevent Small Repairs from Becoming Big Problems", read: "6 min read", views: "9K views", image: img("1600596542815-ffad4c1539a9") },
    { tag: "When to Call a Pro", title: "When Roof Repair Is Not Enough", read: "6 min read", views: "8K views", image: img("1580587771525-78b9dba3b914") },
  ],
  cta: { title: "Need Your Roof Repaired?", desc: "Get a free, no-obligation assessment from our roofing experts.", button: "Get Free Repair Estimate", href: "/estimate/instant" },
  popularHeading: "Popular Repair Topics",
  popular: [
    { label: "Roof Leaks", count: 21 },
    { label: "Damaged Shingles", count: 17 },
    { label: "Flashing Repair", count: 13 },
    { label: "Storm Damage", count: 11 },
    { label: "Roof Vent Repair", count: 9 },
    { label: "Gutter & Drainage Repair", count: 7 },
    { label: "DIY Roof Repair", count: 6 },
    { label: "When to Call a Pro", count: 5 },
  ],
  downloads: [
    { title: "Roof Leak Repair Guide", size: "PDF · 3.1 MB" },
    { title: "Storm Damage Checklist", size: "PDF · 1.6 MB" },
    { title: "DIY Roof Repair Checklist", size: "PDF · 1.2 MB" },
    { title: "Gutter Maintenance Guide", size: "PDF · 2.4 MB" },
  ],
  trust: [
    { icon: "hammer", title: "Step-by-Step Solutions", desc: "Clear, easy-to-follow repair instructions for every roofing problem." },
    { icon: "badge", title: "Expert Reviewed", desc: "All guides are written and reviewed by experienced roofing professionals." },
    { icon: "home", title: "Real Home Scenarios", desc: "Solutions based on real repairs performed across Washington homes." },
    { icon: "calendar", title: "Always Updated", desc: "New content, better solutions, and the latest roofing best practices." },
  ],
  newsletter: {
    title: "Don't Wait for Small Problems to Get Bigger.",
    desc: "Get seasonal maintenance reminders, repair tips, and exclusive content.",
    perks: ["Repair tips & guides", "Seasonal maintenance reminders", "Storm alerts & safety tips", "New articles & videos"],
  },
};

export const SHINGLES: KCCategory = {
  slug: "shingles",
  metaTitle: "Shingle Guides — Knowledge Center",
  metaDesc:
    "Expert asphalt shingle guides for Washington homeowners — types, brands, performance, warranties, installation, colors, and how to choose the right shingle.",
  eyebrow: "Education Center",
  titleLines: ["Shingle Guides"],
  desc: "Everything you need to know about asphalt shingles—materials, types, performance, warranties, installation, maintenance, and how to choose the right shingle for your home.",
  image: img("1570129477492-45c003edd2be"),
  stats: [
    { icon: "document", value: "25+", label: "Expert Guides" },
    { icon: "calendar", value: "Updated", label: "Weekly" },
    { icon: "users", value: "10,000+", label: "Homeowners Helped" },
  ],
  inThisSection: [
    { icon: "layers", label: "Shingle Types" },
    { icon: "home", label: "Architectural Shingles" },
    { icon: "star", label: "Luxury Shingles" },
    { icon: "grid", label: "3-Tab Shingles" },
    { icon: "shield", label: "Impact-Resistant Shingles" },
    { icon: "brush", label: "Color & Style Guide" },
    { icon: "document", label: "Shingle Warranties" },
    { icon: "hammer", label: "Installation & Performance" },
    { icon: "calendar", label: "Maintenance & Care" },
    { icon: "message", label: "FAQ" },
  ],
  searchPlaceholder: "Search shingle articles, types, brands, topics...",
  tabs: ["All Topics", "Types", "Architectural", "Luxury", "3-Tab", "Impact Resistant", "Colors & Styles", "Warranties", "Installation", "Maintenance", "Brands", "FAQ"],
  featuredHeading: "Featured Shingle Guides",
  featuredLabel: "Featured",
  featuredAccent: false,
  featured: [
    { tag: "Types", title: "Architectural vs 3-Tab Shingles: Which One Is Right for You?", read: "12 min read", views: "32K views", image: img("1570129477492-45c003edd2be") },
    { tag: "Materials", title: "Best Asphalt Shingles for Washington Homes (2024 Guide)", read: "11 min read", views: "28K views", image: img("1632759145351-1d592919f522") },
    { tag: "Luxury", title: "Luxury Shingles: Worth the Investment?", read: "10 min read", views: "19K views", image: img("1558036117-15d82a90b9b1") },
    { tag: "Lifespan", title: "How Long Do Shingles Last in Washington?", read: "9 min read", views: "24K views", image: img("1564013799919-ab600027ffc6") },
  ],
  allHeading: "All Shingle Guides",
  all: [
    { tag: "Types", title: "Different Types of Asphalt Shingles Explained", read: "8 min read", views: "18K views", image: img("1570129477492-45c003edd2be") },
    { tag: "Architectural", title: "Anatomy of an Architectural Shingle", read: "7 min read", views: "12K views", image: img("1632759145351-1d592919f522") },
    { tag: "3-Tab", title: "3-Tab Shingles: Pros, Cons & Best Uses", read: "6 min read", views: "10K views", image: img("1558036117-15d82a90b9b1") },
    { tag: "Impact", title: "Impact-Resistant vs Standard Shingles", read: "8 min read", views: "14K views", image: img("1564013799919-ab600027ffc6") },
    { tag: "Colors", title: "How to Choose the Right Shingle Color", read: "7 min read", views: "9K views", image: img("1531971589569-0d9370cbe1e5") },
    { tag: "Brands", title: "Top Shingle Brands in 2024", read: "10 min read", views: "15K views", image: img("1576941089067-2de3c901e126") },
    { tag: "Installation", title: "How Shingles Are Installed: Step-by-Step", read: "11 min read", views: "17K views", image: img("1632759145351-1d592919f522") },
    { tag: "Performance", title: "Wind, Algae & Fire Resistance Ratings Explained", read: "9 min read", views: "8K views", image: img("1583608205776-bfd35f0d9f83") },
    { tag: "Maintenance", title: "How to Clean & Maintain Your Shingles", read: "7 min read", views: "9K views", image: img("1572120360610-d971b9d7767c") },
    { tag: "Granule Loss", title: "Granule Loss: What It Means & What to Do", read: "6 min read", views: "7K views", image: img("1600585154340-be6161a56a0c") },
    { tag: "Warranty", title: "Understanding Shingle Warranties", read: "9 min read", views: "11K views", image: img("1600596542815-ffad4c1539a9") },
    { tag: "Replacement", title: "When to Replace Shingles vs Repair", read: "9 min read", views: "8K views", image: img("1580587771525-78b9dba3b914") },
  ],
  cta: { title: "Not Sure Which Shingle Is Best?", desc: "Our experts can help you choose the perfect shingle for your home and budget.", button: "Get Free Shingle Recommendation", href: "/estimate/instant" },
  popularHeading: "Popular Shingle Topics",
  popular: [
    { label: "Architectural Shingles", count: 16 },
    { label: "Luxury Shingles", count: 13 },
    { label: "3-Tab Shingles", count: 9 },
    { label: "Impact-Resistant Shingles", count: 8 },
    { label: "Shingle Colors", count: 7 },
    { label: "Shingle Warranties", count: 6 },
    { label: "How to Choose", count: 6 },
    { label: "Shingle Lifespan", count: 5 },
  ],
  downloads: [
    { title: "Shingle Buyer's Guide", size: "PDF · 4.2 MB" },
    { title: "Shingle Warranty Guide", size: "PDF · 2.1 MB" },
    { title: "Color Selection Guide", size: "PDF · 3.5 MB" },
    { title: "Shingle Maintenance Guide", size: "PDF · 2.8 MB" },
  ],
  trust: [
    { icon: "badge", title: "Expert Information", desc: "Written by roofing specialists with 15+ years of experience." },
    { icon: "mappin", title: "Local Focused", desc: "Guides tailored for Washington climate and building codes." },
    { icon: "chart", title: "Real Project Data", desc: "Based on thousands of local roof inspections and installations." },
    { icon: "calendar", title: "Always Updated", desc: "Content reviewed weekly so you always get the latest information." },
  ],
  newsletter: {
    title: "Stay Informed. Protect Your Home.",
    desc: "Get seasonal tips, maintenance reminders, and exclusive roofing content.",
    perks: ["New articles & guides", "Seasonal maintenance reminders", "Storm alerts & safety tips", "Exclusive discounts"],
  },
};

export const METAL_ROOFING: KCCategory = {
  slug: "metal-roofing",
  metaTitle: "Metal Roofing Guides — Knowledge Center",
  metaDesc:
    "Expert metal roofing guides for Washington homeowners — standing seam, metal types, costs, installation, maintenance, and how to choose the best metal roof system.",
  eyebrow: "Education Center",
  titleLines: ["Metal Roofing", "Guides"],
  desc: "Everything you need to know about metal roofing—standing seam, corrugated, metal shingles, costs, installation, maintenance, and how to choose the best system for your home.",
  image: img("1576941089067-2de3c901e126"),
  stats: [
    { icon: "document", value: "30+", label: "Expert Guides" },
    { icon: "calendar", value: "Updated", label: "Weekly" },
    { icon: "users", value: "8,000+", label: "Homeowners Helped" },
  ],
  inThisSection: [
    { icon: "layers", label: "Standing Seam" },
    { icon: "grid", label: "Metal Roof Types" },
    { icon: "star", label: "Benefits of Metal Roofing" },
    { icon: "dollar", label: "Costs & Pricing" },
    { icon: "hammer", label: "Installation Process" },
    { icon: "home", label: "Metal vs Shingle" },
    { icon: "calendar", label: "Maintenance & Care" },
    { icon: "wind", label: "Noise & Insulation" },
    { icon: "shield", label: "Warranties" },
    { icon: "camera", label: "Case Studies" },
    { icon: "message", label: "FAQ" },
  ],
  searchPlaceholder: "Search metal roofing articles, systems, costs...",
  tabs: ["All Topics", "Standing Seam", "Metal Types", "Costs", "Installation", "Benefits", "Maintenance", "Design", "Comparison", "Case Studies", "FAQ"],
  featuredHeading: "Featured Metal Roofing Guides",
  featuredLabel: "Featured",
  featuredAccent: false,
  featured: [
    { tag: "Standing Seam", title: "Standing Seam Metal Roofing: Complete Homeowner Guide", read: "11 min read", views: "28K views", image: img("1576941089067-2de3c901e126") },
    { tag: "Costs", title: "Metal Roofing Cost in Washington: 2024 Complete Guide", read: "10 min read", views: "22K views", image: img("1632759145351-1d592919f522") },
    { tag: "Comparison", title: "Metal Roofing vs Asphalt Shingles: Which Is Better?", read: "9 min read", views: "24K views", image: img("1570129477492-45c003edd2be") },
    { tag: "Benefits", title: "Top 7 Benefits of Metal Roofing for Your Home", read: "8 min read", views: "19K views", image: img("1600596542815-ffad4c1539a9") },
  ],
  allHeading: "All Metal Roofing Guides",
  all: [
    { tag: "Standing Seam", title: "Standing Seam vs Exposed Fastener: Key Differences", read: "7 min read", views: "11K views", image: img("1576941089067-2de3c901e126") },
    { tag: "Metal Types", title: "Different Types of Metal Roofing Explained", read: "8 min read", views: "9K views", image: img("1632759145351-1d592919f522") },
    { tag: "Installation", title: "Metal Roof Installation Process: Step-by-Step", read: "10 min read", views: "13K views", image: img("1564013799919-ab600027ffc6") },
    { tag: "Costs", title: "How Much Does a Metal Roof Cost in Washington?", read: "9 min read", views: "15K views", image: img("1570129477492-45c003edd2be") },
    { tag: "Durability", title: "How Long Does a Metal Roof Last?", read: "6 min read", views: "8K views", image: img("1531971589569-0d9370cbe1e5") },
    { tag: "Noise", title: "Is Metal Roofing Noisy? The Truth Explained", read: "6 min read", views: "7K views", image: img("1558036117-15d82a90b9b1") },
    { tag: "Insulation", title: "Metal Roofing and Insulation: What You Need to Know", read: "7 min read", views: "6K views", image: img("1632759145351-1d592919f522") },
    { tag: "Energy Efficiency", title: "How Metal Roofing Improves Energy Efficiency", read: "6 min read", views: "7K views", image: img("1600585154340-be6161a56a0c") },
    { tag: "Maintenance", title: "Metal Roof Maintenance Guide: Keep It Like New", read: "7 min read", views: "6K views", image: img("1576941089067-2de3c901e126") },
    { tag: "Colors", title: "Best Metal Roof Colors for Washington Homes", read: "6 min read", views: "5K views", image: img("1583608205776-bfd35f0d9f83") },
    { tag: "Case Study", title: "Real Metal Roofing Projects in Washington", read: "9 min read", views: "9K views", image: img("1600596542815-ffad4c1539a9") },
    { tag: "Warranty", title: "Understanding Metal Roof Warranties", read: "6 min read", views: "5K views", image: img("1580587771525-78b9dba3b914") },
  ],
  cta: { title: "Considering a Metal Roof?", desc: "Get a free, no-obligation estimate and expert recommendation.", button: "Get Free Metal Roof Estimate", href: "/estimate/instant" },
  popularHeading: "Popular Metal Roof Topics",
  popular: [
    { label: "Standing Seam Metal Roofing", count: 16 },
    { label: "Metal Roofing Cost", count: 13 },
    { label: "Benefits of Metal Roofing", count: 12 },
    { label: "Metal vs Shingle Roofing", count: 9 },
    { label: "Metal Roof Installation", count: 8 },
    { label: "Metal Roof Maintenance", count: 7 },
    { label: "Metal Roofing Colors", count: 6 },
    { label: "Metal Roof Lifespan", count: 5 },
  ],
  downloads: [
    { title: "Metal Roofing Buyer's Guide", size: "PDF · 4.5 MB" },
    { title: "Metal Roof Cost Breakdown", size: "PDF · 2.1 MB" },
    { title: "Metal Roofing Maintenance Guide", size: "PDF · 2.6 MB" },
    { title: "Metal Roof Color Guide", size: "PDF · 3.2 MB" },
  ],
  trust: [
    { icon: "badge", title: "Expert Information", desc: "Written by roofing specialists with 15+ years of experience." },
    { icon: "chart", title: "Real Project Data", desc: "Based on actual projects completed across Washington homes." },
    { icon: "calendar", title: "Always Updated", desc: "We update content weekly to reflect the latest pricing, materials, and best practices." },
    { icon: "mappin", title: "Local Focused", desc: "Guides tailored for Washington climate and building codes." },
  ],
  newsletter: {
    title: "Stay Ahead with Expert Roofing Advice.",
    desc: "Get seasonal tips, maintenance reminders, and exclusive metal roofing insights.",
    perks: ["New articles & guides", "Seasonal maintenance reminders", "Storm alerts & safety tips", "Exclusive offers"],
  },
};

export const SKYLIGHTS: KCCategory = {
  slug: "skylights",
  metaTitle: "Skylight Guides — Knowledge Center",
  metaDesc:
    "Expert skylight guides for Washington homeowners — types, installation, leak solutions, maintenance, placement, ventilation, and product comparisons.",
  eyebrow: "Education Center",
  titleLines: ["Skylight Guides"],
  desc: "Expert advice, installation tips, leak solutions, product comparisons, and maintenance guidance to help you bring more natural light into your home—without the leaks.",
  image: img("1600585154340-be6161a56a0c"),
  stats: [
    { icon: "document", value: "20+", label: "Expert Guides" },
    { icon: "calendar", value: "Updated", label: "Weekly" },
    { icon: "users", value: "6,000+", label: "Homeowners Helped" },
  ],
  inThisSection: [
    { icon: "layers", label: "Skylight Types" },
    { icon: "hammer", label: "Skylight Installation" },
    { icon: "droplet", label: "Skylight Leaks & Repair" },
    { icon: "calendar", label: "Skylight Maintenance" },
    { icon: "star", label: "Best Skylights" },
    { icon: "dollar", label: "Skylight Cost & Pricing" },
    { icon: "mappin", label: "Skylight Placement" },
    { icon: "wind", label: "Skylights & Ventilation" },
    { icon: "sun", label: "Solar Powered Skylights" },
    { icon: "camera", label: "Case Studies" },
    { icon: "message", label: "FAQ" },
  ],
  searchPlaceholder: "Search skylight articles, installation, leaks, types...",
  tabs: ["All Topics", "Types", "Installation", "Leaks & Repair", "Maintenance", "Costs", "Placement", "Ventilation", "Solar Skylights", "Brands", "FAQ"],
  featuredHeading: "Featured Skylight Guides",
  featuredLabel: "Featured",
  featuredAccent: false,
  featured: [
    { tag: "Types", title: "Complete Guide to Skylights: Types, Benefits & Costs", read: "11 min read", views: "22K views", image: img("1600585154340-be6161a56a0c") },
    { tag: "Leaks & Repair", title: "Skylight Leaking? How to Find and Fix the Problem for Good", read: "9 min read", views: "18K views", image: img("1564013799919-ab600027ffc6") },
    { tag: "Best Skylights", title: "Best Skylights for Washington Homes (2024 Guide)", read: "10 min read", views: "16K views", image: img("1600585154340-be6161a56a0c") },
    { tag: "Installation", title: "Skylight Installation Process: What to Expect Step-by-Step", read: "8 min read", views: "14K views", image: img("1531971589569-0d9370cbe1e5") },
  ],
  allHeading: "All Skylight Guides",
  all: [
    { tag: "Types", title: "Different Types of Skylights: Which One Is Right for You?", read: "8 min read", views: "12K views", image: img("1600585154340-be6161a56a0c") },
    { tag: "Installation", title: "Skylight Installation Do's and Don'ts", read: "7 min read", views: "9K views", image: img("1531971589569-0d9370cbe1e5") },
    { tag: "Leaks & Repair", title: "How to Stop a Skylight Leak (Permanent Solutions)", read: "7 min read", views: "9K views", image: img("1632759145351-1d592919f522") },
    { tag: "Maintenance", title: "Skylight Maintenance Tips to Extend Its Life", read: "6 min read", views: "8K views", image: img("1600585154340-be6161a56a0c") },
    { tag: "Costs", title: "How Much Does a Skylight Cost in Washington?", read: "6 min read", views: "8K views", image: img("1564013799919-ab600027ffc6") },
    { tag: "Placement", title: "Best Skylight Placement for Natural Light and Energy Efficiency", read: "6 min read", views: "7K views", image: img("1600585154340-be6161a56a0c") },
    { tag: "Ventilation", title: "Ventilated vs Fixed Skylights: Which One Do You Need?", read: "7 min read", views: "7K views", image: img("1600585154340-be6161a56a0c") },
    { tag: "Solar", title: "Solar Powered Skylights: Benefits, Costs & Top Brands", read: "6 min read", views: "6K views", image: img("1531971589569-0d9370cbe1e5") },
    { tag: "Brands", title: "Best Skylight Brands in 2024 (Velux, Fakro & More)", read: "7 min read", views: "6K views", image: img("1600585154340-be6161a56a0c") },
    { tag: "Design", title: "Skylights in Different Rooms: Ideas & Inspiration", read: "7 min read", views: "5K views", image: img("1564013799919-ab600027ffc6") },
    { tag: "Energy Efficiency", title: "How Skylights Improve Energy Efficiency in Your Home", read: "6 min read", views: "5K views", image: img("1600585154340-be6161a56a0c") },
    { tag: "Case Study", title: "Real Skylight Projects in Washington Homes", read: "6 min read", views: "5K views", image: img("1600596542815-ffad4c1539a9") },
  ],
  cta: { title: "Planning a Skylight Project?", desc: "Get a free, no-obligation estimate from our skylight experts.", button: "Get Free Skylight Estimate", href: "/estimate/instant" },
  popularHeading: "Popular Skylight Topics",
  popular: [
    { label: "Skylight Leaks", count: 16 },
    { label: "Skylight Installation", count: 13 },
    { label: "Types of Skylights", count: 11 },
    { label: "Skylight Cost", count: 9 },
    { label: "Skylight Maintenance", count: 8 },
    { label: "Skylight Placement", count: 7 },
    { label: "Best Skylights", count: 6 },
    { label: "Ventilated Skylights", count: 5 },
  ],
  downloads: [
    { title: "Skylight Buyer's Guide", size: "PDF · 3.6 MB" },
    { title: "Skylight Leak Repair Guide", size: "PDF · 2.1 MB" },
    { title: "Skylight Maintenance Checklist", size: "PDF · 1.6 MB" },
    { title: "Skylight Installation Guide", size: "PDF · 4.2 MB" },
  ],
  trust: [
    { icon: "badge", title: "Expert Written", desc: "All content is written and reviewed by roofing and skylight specialists with 15+ years of experience." },
    { icon: "chart", title: "Real Project Data", desc: "Guides based on thousands of actual skylight installations and repairs." },
    { icon: "calendar", title: "Always Updated", desc: "We update our guides weekly to reflect new products, techniques, and best practices." },
    { icon: "mappin", title: "Local Focused", desc: "Content tailored for Washington homes and building codes." },
  ],
  newsletter: {
    title: "Bring More Natural Light, Not More Problems.",
    desc: "Get tips, seasonal reminders, and exclusive skylight advice.",
    perks: ["New articles & guides", "Seasonal maintenance reminders", "Exclusive tips & offers", "Leak prevention advice"],
  },
};

export const STORM_DAMAGE: KCCategory = {
  slug: "storm-damage",
  metaTitle: "Storm Damage Guides — Knowledge Center",
  metaDesc:
    "Expert storm damage guides for Washington homeowners — identifying, documenting, and repairing wind, hail, and fallen-tree damage, plus insurance claims help.",
  eyebrow: "Education Center",
  titleLines: ["Storm Damage", "Guides"],
  desc: "Storms can cause hidden damage your roof can't always catch. Get expert guidance on identifying, documenting, and repairing storm damage to protect your home and maximize insurance coverage.",
  image: img("1632759145351-1d592919f522"),
  stats: [
    { icon: "document", value: "25+", label: "Expert Guides" },
    { icon: "cloud", value: "Updated", label: "After Every Storm" },
    { icon: "users", value: "8,000+", label: "Homeowners Helped" },
  ],
  inThisSection: [
    { icon: "cloud", label: "Storm Damage Types" },
    { icon: "home", label: "After the Storm: What to Do" },
    { icon: "search", label: "How to Inspect Your Roof" },
    { icon: "shield", label: "Insurance & Claims" },
    { icon: "document", label: "Documentation Guide" },
    { icon: "wrench", label: "Emergency Repairs" },
    { icon: "snow", label: "Hail Damage" },
    { icon: "wind", label: "Wind Damage" },
    { icon: "leaf", label: "Fallen Tree Damage" },
    { icon: "camera", label: "Case Studies" },
    { icon: "message", label: "FAQs" },
  ],
  searchPlaceholder: "Search storm damage articles, leaks, hail, wind, claims...",
  tabs: ["All Topics", "Storm Damage Types", "Wind Damage", "Hail Damage", "What to Do", "Insurance & Claims", "Inspection", "Repairs", "Prevention", "FAQ"],
  featuredHeading: "Featured Storm Damage Guides",
  featuredLabel: "Featured",
  featuredAccent: false,
  featured: [
    { tag: "Basics", title: "Storm Damage 101: What Homeowners Need to Know", read: "10 min read", views: "32K views", image: img("1632759145351-1d592919f522") },
    { tag: "Inspection", title: "How to Inspect Your Roof after a Storm", read: "9 min read", views: "24K views", image: img("1570129477492-45c003edd2be") },
    { tag: "Hail Damage", title: "Hail Damage: What It Looks Like & What to Do", read: "9 min read", views: "21K views", image: img("1558036117-15d82a90b9b1") },
    { tag: "Insurance", title: "Does Insurance Cover Storm Damage? A Complete Guide", read: "11 min read", views: "28K views", image: img("1600596542815-ffad4c1539a9") },
  ],
  allHeading: "All Storm Damage Guides",
  all: [
    { tag: "Wind Damage", title: "Wind Damage on Roofs: Signs, Causes & Repairs", read: "8 min read", views: "16K views", image: img("1632759145351-1d592919f522") },
    { tag: "Hail Damage", title: "Hail Damage vs Normal Wear: How to Tell the Difference", read: "7 min read", views: "14K views", image: img("1558036117-15d82a90b9b1") },
    { tag: "Fallen Trees", title: "What to Do When a Tree Falls on Your Roof", read: "9 min read", views: "12K views", image: img("1572120360610-d971b9d7767c") },
    { tag: "Leaks After Storm", title: "Roof Leaks After a Storm: Common Causes and Solutions", read: "8 min read", views: "11K views", image: img("1564013799919-ab600027ffc6") },
    { tag: "Inspection", title: "Professional Storm Inspection: What We Look For", read: "7 min read", views: "9K views", image: img("1570129477492-45c003edd2be") },
    { tag: "Insurance", title: "How to File a Roof Insurance Claim (Step-by-Step)", read: "10 min read", views: "18K views", image: img("1531971589569-0d9370cbe1e5") },
    { tag: "Documentation", title: "How to Document Storm Damage for Insurance Claims", read: "7 min read", views: "13K views", image: img("1576941089067-2de3c901e126") },
    { tag: "Emergency Repair", title: "Emergency Roof Repairs: Temporary Fixes That Protect Your Home", read: "6 min read", views: "8K views", image: img("1583608205776-bfd35f0d9f83") },
    { tag: "Shingle Damage", title: "Missing Shingles After a Storm: What It Means", read: "6 min read", views: "7K views", image: img("1632759145351-1d592919f522") },
    { tag: "Case Study", title: "Real Storm Damage Case Study: Bellevue, Washington", read: "8 min read", views: "6K views", image: img("1600596542815-ffad4c1539a9") },
    { tag: "Case Study", title: "How We Helped a Family After a Windstorm in Kirkland, WA", read: "7 min read", views: "4K views", image: img("1570129477492-45c003edd2be") },
    { tag: "Safety", title: "Storm Safety: What Homeowners Should Avoid", read: "6 min read", views: "4K views", image: img("1580587771525-78b9dba3b914") },
  ],
  cta: { title: "Think Your Roof Has Storm Damage?", desc: "Get a free, no-obligation roof inspection and expert assessment.", button: "Get Free Inspection", href: liveHref("/services/roof-inspection", "/contact") },
  popularHeading: "Popular Topics",
  popular: [
    { label: "Wind Damage", count: 16 },
    { label: "Hail Damage", count: 14 },
    { label: "Insurance Claims", count: 12 },
    { label: "Storm Inspection", count: 11 },
    { label: "Emergency Repairs", count: 10 },
    { label: "Documentation", count: 8 },
    { label: "Fallen Tree Damage", count: 7 },
    { label: "Leak After Storm", count: 6 },
  ],
  downloads: [
    { title: "Storm Damage Checklist", size: "PDF · 2.1 MB" },
    { title: "Insurance Claim Guide", size: "PDF · 3.4 MB" },
    { title: "Hail Damage Photo Guide", size: "PDF · 1.8 MB" },
    { title: "Emergency Roof Repair Guide", size: "PDF · 2.6 MB" },
  ],
  trust: [
    { icon: "badge", title: "Real Expert Advice", desc: "Written by roofing professionals with 15+ years of experience." },
    { icon: "mappin", title: "Local Washington Focused", desc: "Content tailored for Washington weather, building codes, and insurance providers." },
    { icon: "chart", title: "Real Project Data", desc: "Based on actual storm damage inspections and repair projects across WA." },
    { icon: "calendar", title: "Always Updated", desc: "We update guides after major storms with new data and insurance insights." },
  ],
  newsletter: {
    title: "Stay Ahead of the Next Storm.",
    desc: "Get storm alerts, maintenance reminders, and expert roofing tips.",
    perks: ["Storm alerts & warnings", "Seasonal maintenance reminders", "New guides & articles", "Exclusive tips & offers"],
  },
};

export const HOMEOWNER: KCCategory = {
  slug: "homeowner",
  metaTitle: "Homeowner Guides — Knowledge Center",
  metaDesc:
    "Practical roofing guides for Washington homeowners — replacement, maintenance, repair, storm damage, costs & financing, insurance, buying & selling, and seasonal care.",
  eyebrow: "Education Center",
  titleLines: ["Homeowner", "Guides"],
  desc: "Practical guides and expert advice to help homeowners protect their homes, plan for the future, and make smart decisions about their roofs and exteriors.",
  image: img("1600596542815-ffad4c1539a9"),
  stats: [
    { icon: "document", value: "40+", label: "Expert Guides" },
    { icon: "calendar", value: "Updated", label: "Weekly" },
    { icon: "users", value: "15,000+", label: "Homeowners Helped" },
  ],
  inThisSection: [
    { icon: "home", label: "Roof Replacement" },
    { icon: "calendar", label: "Roof Maintenance" },
    { icon: "wrench", label: "Roof Repair" },
    { icon: "cloud", label: "Storm Damage" },
    { icon: "dollar", label: "Costs & Financing" },
    { icon: "shield", label: "Insurance & Claims" },
    { icon: "users", label: "Before You Hire" },
    { icon: "wallet", label: "Buying & Selling" },
    { icon: "sun", label: "Seasonal Care" },
    { icon: "hammer", label: "Home Improvement" },
    { icon: "message", label: "FAQs for Homeowners" },
  ],
  searchPlaceholder: "Search homeowner guides, topics, questions...",
  tabs: ["All Topics", "Popular Guides", "Roof Replacement", "Maintenance", "Costs & Financing", "Insurance & Claims", "Buying & Selling", "Seasonal Care", "Home Improvement", "FAQ"],
  featuredHeading: "Popular Homeowner Guides",
  featuredLabel: "Popular",
  featuredAccent: false,
  featured: [
    { tag: "Cost", title: "How Much Does a New Roof Cost in Washington State?", read: "10 min read", views: "28K views", image: img("1600596542815-ffad4c1539a9") },
    { tag: "Replacement", title: "Signs You Need a New Roof (Don't Ignore These 12 Things)", read: "9 min read", views: "24K views", image: img("1570129477492-45c003edd2be") },
    { tag: "Process", title: "Roof Replacement Timeline: What to Expect Step-by-Step", read: "9 min read", views: "20K views", image: img("1632759145351-1d592919f522") },
    { tag: "Hiring", title: "How to Choose the Right Roofing Contractor in Washington", read: "10 min read", views: "18K views", image: img("1564013799919-ab600027ffc6") },
  ],
  allHeading: "All Homeowner Guides",
  all: [
    { tag: "Replacement", title: "Complete Guide to Roof Replacement for Homeowners", read: "12 min read", views: "22K views", image: img("1570129477492-45c003edd2be") },
    { tag: "Maintenance", title: "Roof Maintenance Checklist: Monthly, Seasonal & Yearly", read: "7 min read", views: "16K views", image: img("1632759145351-1d592919f522") },
    { tag: "Warranty", title: "Understanding Roofing Warranties: What's Covered & What's Not", read: "9 min read", views: "14K views", image: img("1558036117-15d82a90b9b1") },
    { tag: "Lifespan", title: "How Long Does a Roof Last in Washington? (By Material)", read: "8 min read", views: "13K views", image: img("1576941089067-2de3c901e126") },
    { tag: "Repair", title: "Is Roof Repair Enough or Do You Need a Replacement?", read: "8 min read", views: "11K views", image: img("1564013799919-ab600027ffc6") },
    { tag: "Insurance", title: "How Insurance Roof Claims Work: A Homeowner's Guide", read: "10 min read", views: "11K views", image: img("1531971589569-0d9370cbe1e5") },
    { tag: "Storm Damage", title: "What to Do After a Storm: 7 Steps for Homeowners", read: "7 min read", views: "10K views", image: img("1632759145351-1d592919f522") },
    { tag: "Weather", title: "How Weather in Washington Affects Your Roof", read: "8 min read", views: "9K views", image: img("1600585154340-be6161a56a0c") },
    { tag: "Maintenance", title: "Can Moss Damage Your Roof? What Homeowners Should Know", read: "6 min read", views: "8K views", image: img("1572120360610-d971b9d7767c") },
    { tag: "Financing", title: "Roof Financing Options: How to Pay Without the Stress", read: "7 min read", views: "7K views", image: img("1583608205776-bfd35f0d9f83") },
    { tag: "Buying & Selling", title: "Buying or Selling a Home? Don't Forget the Roof", read: "7 min read", views: "6K views", image: img("1600596542815-ffad4c1539a9") },
    { tag: "Home Value", title: "Increase Home Value with a New Roof: Here's How", read: "6 min read", views: "6K views", image: img("1570129477492-45c003edd2be") },
    { tag: "Seasonal", title: "Summer Roofing Tips to Protect Your Home", read: "6 min read", views: "5K views", image: img("1564013799919-ab600027ffc6") },
    { tag: "Seasonal", title: "Winter Roofing Care: Prepare Your Home for Cold Weather", read: "6 min read", views: "5K views", image: img("1580587771525-78b9dba3b914") },
    { tag: "FAQ", title: "Top 10 Questions Homeowners Ask About Roofing", read: "6 min read", views: "5K views", image: img("1531971589569-0d9370cbe1e5") },
  ],
  cta: { title: "Protect Your Home With Confidence", desc: "Get a free, no-obligation roof inspection and expert recommendations.", button: "Get Free Inspection", href: liveHref("/services/roof-inspection", "/contact") },
  popularHeading: "Trending Homeowner Topics",
  popular: [
    { label: "Roof Replacement", count: 22 },
    { label: "Roof Maintenance", count: 18 },
    { label: "Costs & Financing", count: 16 },
    { label: "Storm Damage", count: 15 },
    { label: "Roof Repair", count: 12 },
    { label: "Insurance & Claims", count: 11 },
    { label: "Before You Hire", count: 9 },
    { label: "Buying & Selling", count: 8 },
  ],
  downloads: [
    { title: "Homeowner Roofing Guide", size: "PDF · 3.8 MB" },
    { title: "Roof Maintenance Checklist", size: "PDF · 1.6 MB" },
    { title: "Roof Replacement Checklist", size: "PDF · 2.1 MB" },
    { title: "Storm Damage Guide", size: "PDF · 2.4 MB" },
  ],
  trust: [
    { icon: "badge", title: "Expert Information", desc: "Guides written & reviewed by roofing professionals with 15+ years of experience." },
    { icon: "mappin", title: "Local Washington Focused", desc: "Content tailored for Washington weather, building codes, and homeowner needs." },
    { icon: "home", title: "Real Home Scenarios", desc: "Based on real projects and homeowner questions from across WA." },
    { icon: "calendar", title: "Always Updated", desc: "New content added weekly to keep you informed and protected." },
  ],
  newsletter: {
    title: "Stay Informed. Protect Your Home.",
    desc: "Get expert tips, seasonal reminders, and exclusive homeowner guides.",
    perks: ["New articles & guides", "Seasonal maintenance tips", "Storm alerts", "Exclusive offers"],
  },
};

export const KC_CATEGORY_PAGES: Record<string, KCCategory> = {
  "roof-replacement": ROOF_REPLACEMENT,
  "roof-repair": ROOF_REPAIR,
  "shingles": SHINGLES,
  "metal-roofing": METAL_ROOFING,
  "skylights": SKYLIGHTS,
  "storm-damage": STORM_DAMAGE,
  "homeowner": HOMEOWNER,
};

export const getKCCategory = (slug: string) => KC_CATEGORY_PAGES[slug];
