/* Material pages template (/materials/[material]) — mock content.
   Manufacturer names shown as text placeholders (no logo art). */

const img = (id: string) => `/images/${id}.jpg`;

export type MaterialPage = {
  slug: string;
  eyebrow: string;
  breadcrumbParent?: { label: string; href: string };
  titleLines: string[];
  sub: string;
  heroImage: string;
  whyCard: { title: string; items: string[] };
  brandsHeading: string;
  brands: string[];
  features: { icon?: string; title: string; desc: string; checklist: string[]; image: string }[];
  typesHeading: string;
  types: { title: string; brand?: string; desc: string; checklist: string[]; image: string }[];
  colorsHeading: string;
  colorsNote?: string;
  colors: { name: string; hex: string }[];
  comparison: {
    title: string;
    columns: string[];
    rows: { icon: string; feature: string; values: string[] }[];
  };
  processTitle: string;
  processIntro: string;
  process: { n: number; icon: string; title: string; desc: string }[];
  processImage?: string;
  processTagline?: string;
  processCardText?: string;
  standBehind?: { title: string; text: string; badge: string };
  warranty: { title: string; text: string; tiers: { years: string; label: string }[] };
  projectsHeading: string;
  projects: string[];
  reviewsHeading?: string;
  review: { name: string; city: string; initials: string; quote: string };
  ctaTitle: string;
  ctaSubtitle: string;
  ctaTrust: { icon: string; label: string }[];
};

export const ARCHITECTURAL_SHINGLES: MaterialPage = {
  slug: "architectural-shingles",
  eyebrow: "Architectural Shingles",
  titleLines: ["Elevated Beauty.", "Superior Protection."],
  sub: "Architectural shingles—also known as dimensional shingles—offer a thicker, layered look that adds depth and character to your home while delivering outstanding durability and performance.",
  heroImage: img("1568605114967-8130f3a36994"),
  whyCard: {
    title: "Why Architectural Shingles?",
    items: [
      "Thicker and more durable",
      "High wind and impact resistance",
      "Enhanced curb appeal",
      "Longer lifespan",
      "Better protection for your home",
      "Great warranty options",
    ],
  },
  brandsHeading: "We Install Premium Architectural Shingles From Trusted Brands",
  brands: ["CertainTeed", "GAF", "Malarkey", "IKO", "Owens Corning"],
  features: [
    { title: "Dimensional Beauty", desc: "Multi-layered design creates depth, dimension, and a high-end look for any style of home.", checklist: ["Thicker than 3-tab shingles", "Architectural style and dimension", "Adds value and curb appeal", "Wide range of colors"], image: img("1572120360610-d971b9d7767c") },
    { title: "Built To Perform", desc: "Engineered for superior strength and weather protection in all seasons.", checklist: ["High wind resistance up to 130 MPH+", "Impact resistant", "Algae & moss resistance options", "Fire resistant ratings"], image: img("1576941089067-2de3c901e126") },
    { title: "Long-Term Value", desc: "Architectural shingles offer a longer lifespan and better warranty coverage.", checklist: ["25–50 year limited warranties", "Lower maintenance", "Better protection = fewer repairs", "Excellent return on investment"], image: img("1583608205776-bfd35f0d9f83") },
  ],
  typesHeading: "Architectural Shingle Types",
  types: [
    { title: "Standard Architectural", desc: "The perfect balance of performance, protection, and value.", checklist: ["Great everyday protection", "Variety of colors", "30–50 year warranty"], image: img("1568605114967-8130f3a36994") },
    { title: "Premium Architectural", desc: "Upscale appearance with enhanced weather resistance.", checklist: ["Thicker and heavier", "Superior durability", "Enhanced curb appeal", "40–50 year warranty"], image: img("1572120360610-d971b9d7767c") },
    { title: "Luxury Architectural", desc: "High-end design with advanced protection and performance.", checklist: ["Maximum thickness", "Designer colors", "Algae & impact protection", "Lifetime limited warranty"], image: img("1583608205776-bfd35f0d9f83") },
    { title: "Impact Resistant", desc: "Built for areas prone to hail, storms, and severe weather.", checklist: ["Class 4 impact rating", "Helps lower insurance premiums", "Maximum durability", "Long-lasting protection"], image: img("1576941089067-2de3c901e126") },
  ],
  colorsHeading: "Popular Architectural Shingle Colors",
  colors: [
    { name: "Weathered Wood", hex: "#6b5d4f" },
    { name: "Pewter Gray", hex: "#8a8d8f" },
    { name: "Charcoal", hex: "#3a3d40" },
    { name: "Driftwood", hex: "#9a8b76" },
    { name: "Brownwood", hex: "#6e4b34" },
    { name: "Dual Black", hex: "#1f2124" },
    { name: "Moire Black", hex: "#26282b" },
    { name: "Slate", hex: "#55606b" },
    { name: "Shakewood", hex: "#7d6650" },
  ],
  comparison: {
    title: "Architectural vs. 3-Tab Shingles",
    columns: ["Architectural Shingles", "3-Tab Shingles"],
    rows: [
      { icon: "layers", feature: "Thickness", values: ["Thicker, multi-layered", "Thin, single layer"] },
      { icon: "home", feature: "Appearance", values: ["Dimensional, high-end look", "Flat, uniform look"] },
      { icon: "wind", feature: "Wind Resistance", values: ["Up to 130 MPH+", "Up to 60–70 MPH"] },
      { icon: "clock", feature: "Lifespan", values: ["25–50+ years", "15–20 years"] },
      { icon: "shield", feature: "Warranty", values: ["Limited Lifetime", "15–25 years"] },
      { icon: "star", feature: "Curb Appeal", values: ["High", "Basic"] },
      { icon: "dollar", feature: "Value", values: ["Higher return on investment", "Lower initial cost"] },
    ],
  },
  processTitle: "Our Installation Process",
  processIntro: "Expert installation for maximum performance and longevity.",
  process: [
    { n: 1, icon: "search", title: "Inspection", desc: "We evaluate your roof and recommend the best solution." },
    { n: 2, icon: "wrench", title: "Preparation", desc: "We remove old materials and inspect the deck." },
    { n: 3, icon: "layers", title: "Underlayment", desc: "High-quality underlayment for added protection." },
    { n: 4, icon: "hammer", title: "Installation", desc: "Precision installation of architectural shingles." },
    { n: 5, icon: "badge", title: "Quality Check", desc: "We inspect every detail to ensure excellence." },
    { n: 6, icon: "trash", title: "Clean Up", desc: "We leave your property clean and protected." },
  ],
  warranty: {
    title: "Strong Warranties. Total Peace Of Mind.",
    text: "We offer industry-leading warranties that protect your home and your investment for decades.",
    tiers: [
      { years: "25-30 Year", label: "Standard Warranty" },
      { years: "40-50 Year", label: "Premium Warranty" },
      { years: "50 Year", label: "Non-Prorated Warranty" },
    ],
  },
  projectsHeading: "Recent Architectural Shingle Projects",
  projects: [img("1568605114967-8130f3a36994"), img("1572120360610-d971b9d7767c"), img("1583608205776-bfd35f0d9f83")],
  review: {
    name: "Jennifer L.",
    city: "Kirkland, WA",
    initials: "JL",
    quote: "We chose architectural shingles for our home and couldn't be happier. The team at Skyve was professional, efficient, and the results are stunning!",
  },
  ctaTitle: "Ready To Upgrade Your Roof?",
  ctaSubtitle: "Architectural shingles deliver beauty, performance, and long-lasting protection for your home.",
  ctaTrust: [
    { icon: "badge", label: "No Obligation Estimate" },
    { icon: "zap", label: "Fast & Easy Process" },
    { icon: "mappin", label: "Local Roofing Experts" },
  ],
};

export const LUXURY_SHINGLES: MaterialPage = {
  slug: "luxury-shingles",
  eyebrow: "Luxury Shingles",
  titleLines: ["Unmatched Elegance.", "Uncompromising Protection."],
  sub: "Luxury shingles combine premium materials, advanced engineering, and striking beauty to create a roof that elevates your home in every way.",
  heroImage: img("1580587771525-78b9dba3b914"),
  whyCard: {
    title: "The Luxury Difference",
    items: [
      "Exceptional beauty and depth",
      "Superior durability & longevity",
      "Enhanced curb appeal",
      "Advanced protection",
      "Strong warranties",
      "A smart investment",
    ],
  },
  brandsHeading: "We Install The Industry's Finest Luxury Shingles",
  brands: ["CertainTeed", "GAF", "Malarkey", "IKO", "Owens Corning"],
  features: [
    { title: "Premium Materials", desc: "Luxury shingles are crafted with the highest quality materials for exceptional performance.", checklist: ["Thick, multi-layer construction", "Premium granule blends", "Enhanced color depth", "Maximum durability"], image: img("1576941089067-2de3c901e126") },
    { title: "Outstanding Performance", desc: "Engineered to perform at the highest level in all conditions.", checklist: ["Wind resistance up to 130 MPH+", "Impact and hail resistance", "Algae & moss protection", "Fire resistant ratings"], image: img("1583608205776-bfd35f0d9f83") },
    { title: "Timeless Beauty", desc: "Designed to enhance the architectural beauty and value of your home.", checklist: ["Rich, dimensional profiles", "Designer color collections", "High-end curb appeal", "Adds lasting value"], image: img("1580587771525-78b9dba3b914") },
  ],
  typesHeading: "Luxury Shingle Collections",
  types: [
    { title: "Grand Sequoia®", brand: "CertainTeed", desc: "Bold, thick, and beautifully dimensional for a truly luxurious look.", checklist: ["Extra-thick construction", "Shadow line definition", "Limited Lifetime Warranty", "15-year StreakFighter®"], image: img("1568605114967-8130f3a36994") },
    { title: "Timberline HDZ®", brand: "GAF", desc: "An advanced shingle with industry-leading protection.", checklist: ["LayerLock™ Technology", "Up to 99.9% nail pull-through", "Limited Lifetime Warranty", "15-year StainGuard Plus™"], image: img("1572120360610-d971b9d7767c") },
    { title: "Vista®", brand: "IKO", desc: "High-performance luxury shingles with stunning curb appeal.", checklist: ["ArmourZone® protection", "130 MPH wind resistance", "Limited Lifetime Warranty", "10-year Algae Resistance"], image: img("1583608205776-bfd35f0d9f83") },
    { title: "TruDefinition® Duration®", brand: "Owens Corning", desc: "The perfect balance of luxury and long-lasting performance.", checklist: ["SureNail® Technology", "130 MPH wind resistance", "Limited Lifetime Warranty", "10-year Algae Resistance"], image: img("1576941089067-2de3c901e126") },
  ],
  colorsHeading: "Popular Luxury Colors",
  colors: [
    { name: "Weathered Wood", hex: "#6b5d4f" },
    { name: "Charcoal Black", hex: "#2a2c2f" },
    { name: "Slate", hex: "#55606b" },
    { name: "Barkwood", hex: "#5a4a3a" },
    { name: "Driftwood", hex: "#9a8b76" },
    { name: "Brownstone", hex: "#6e4b34" },
    { name: "Black Walnut", hex: "#3a2e26" },
    { name: "Mission Brown", hex: "#5c4433" },
  ],
  comparison: {
    title: "Luxury vs. Standard Shingles",
    columns: ["Luxury Shingles", "Standard Shingles"],
    rows: [
      { icon: "layers", feature: "Thickness", values: ["Thicker, multi-layered", "Thinner, single layer"] },
      { icon: "home", feature: "Appearance", values: ["Dimensional, high-end look", "Flat, uniform look"] },
      { icon: "wind", feature: "Wind Resistance", values: ["Up to 130 MPH+", "Up to 60–70 MPH"] },
      { icon: "clock", feature: "Lifespan", values: ["30–50+ years", "15–20 years"] },
      { icon: "shield", feature: "Warranty", values: ["Limited Lifetime", "20–30 years"] },
      { icon: "droplet", feature: "Algae Protection", values: ["10–15 years", "5 years"] },
      { icon: "dollar", feature: "Value", values: ["Higher return on investment", "Lower initial cost"] },
    ],
  },
  processTitle: "Our Installation Process",
  processIntro: "Precision installation for maximum beauty and protection.",
  process: [
    { n: 1, icon: "search", title: "Inspection", desc: "We evaluate your roof and recommend the best solution." },
    { n: 2, icon: "wrench", title: "Preparation", desc: "We remove old materials and inspect the roof deck." },
    { n: 3, icon: "layers", title: "Underlayment", desc: "High-quality underlayment for advanced protection." },
    { n: 4, icon: "hammer", title: "Installation", desc: "Expert installation of luxury shingles with precision." },
    { n: 5, icon: "badge", title: "Quality Check", desc: "We inspect every detail to ensure perfection." },
    { n: 6, icon: "trash", title: "Clean Up", desc: "We leave your property clean and protected." },
  ],
  warranty: {
    title: "Strong Warranties. Total Peace Of Mind.",
    text: "We offer industry-leading warranties that protect your home and your investment for decades.",
    tiers: [
      { years: "50-Year", label: "Product Warranty" },
      { years: "15-Year", label: "Algae Resistance Warranty" },
      { years: "130 MPH+", label: "Wind Resistance" },
    ],
  },
  projectsHeading: "Recent Luxury Shingle Projects",
  projects: [img("1580587771525-78b9dba3b914"), img("1568605114967-8130f3a36994"), img("1564013799919-ab600027ffc6")],
  review: {
    name: "Michael T.",
    city: "Bellevue, WA",
    initials: "MT",
    quote: "The luxury shingles gave our home a stunning new look. The quality and installation were top-notch. Highly recommend Skyve Roofing!",
  },
  ctaTitle: "Ready To Upgrade To Luxury?",
  ctaSubtitle: "Luxury shingles deliver beauty, performance, and value that lasts for generations.",
  ctaTrust: [
    { icon: "badge", label: "No Obligation Estimate" },
    { icon: "zap", label: "Fast & Easy Process" },
    { icon: "mappin", label: "Local Roofing Experts" },
  ],
};

export const METAL_ROOFING: MaterialPage = {
  slug: "metal-roofing",
  eyebrow: "Metal Roofing",
  titleLines: ["Stronger. Smarter.", "Built To Last."],
  sub: "Metal roofing delivers unmatched durability, energy efficiency, and modern style. A long-term investment that protects your home and adds value for decades.",
  heroImage: img("1576941089067-2de3c901e126"),
  whyCard: {
    title: "Why Metal Roofing?",
    items: [
      "50+ Year Lifespan",
      "Extreme Weather Resistant",
      "Fire & Impact Resistant",
      "Energy Efficient",
      "Low Maintenance",
      "Eco-Friendly & Recyclable",
      "Increases Home Value",
      "Modern Curb Appeal",
    ],
  },
  brandsHeading: "We Install Premium Metal Roofing Systems From Trusted Brands",
  brands: ["ATAS", "McElroy Metal", "MBCI", "Sherwin-Williams", "ENERGY STAR", "ASC"],
  features: [
    { title: "Built For Extreme Conditions", desc: "Metal roofs are engineered to withstand the toughest weather, from heavy rain to high winds and snow.", checklist: ["140+ MPH wind resistance", "Hail & impact resistant", "Snow shed design", "Salt air corrosion resistant"], image: img("1576941089067-2de3c901e126") },
    { title: "Energy Efficient Year-Round", desc: "Reflects solar heat in summer and retains warmth in winter—helping lower energy bills.", checklist: ["Cool roof reflective coatings", "Reduces attic heat up to 25%", "Lower HVAC energy usage", "ENERGY STAR® compatible"], image: img("1568605114967-8130f3a36994") },
    { title: "A Long-Term Investment", desc: "With a lifespan of 50+ years and minimal maintenance, metal roofing pays for itself over time.", checklist: ["50+ year lifespan", "Low maintenance", "Non-combustible (Class A fire rating)", "100% recyclable materials"], image: img("1583608205776-bfd35f0d9f83") },
  ],
  typesHeading: "Metal Roofing Styles",
  types: [
    { title: "Standing Seam", desc: "Clean lines. Maximum protection. Our most popular metal roofing system.", checklist: ["Concealed fasteners", "Vertical panel design", "Superior leak protection", "Ideal for modern & traditional homes"], image: img("1576941089067-2de3c901e126") },
    { title: "Metal Shingles", desc: "The classic look of shingles with superior metal performance.", checklist: ["Stone-coated steel", "Dimensional appearance", "Lightweight & durable", "Fade & rust resistant"], image: img("1568605114967-8130f3a36994") },
    { title: "Metal Tiles", desc: "Elegant tile style with the strength of metal.", checklist: ["Tile, shake & slate profiles", "High-end curb appeal", "Long-lasting color", "Fire & impact resistant"], image: img("1572120360610-d971b9d7767c") },
    { title: "R-Panel (Exposed Fastener)", desc: "Cost-effective & reliable for many residential applications.", checklist: ["Exposed fastener system", "Rugged & durable", "Great for barns & cabins", "Budget-friendly option"], image: img("1583608205776-bfd35f0d9f83") },
    { title: "Metal Shake", desc: "Premium shake look with zero wood maintenance.", checklist: ["Textured shake panels", "Hail, fire & rot resistant", "Natural appearance", "50+ year lifespan"], image: img("1600585154340-be6161a56a0c") },
  ],
  colorsHeading: "Popular Metal Colors",
  colors: [
    { name: "Matte Black", hex: "#26282b" },
    { name: "Charcoal Gray", hex: "#4a4d50" },
    { name: "Slate Gray", hex: "#6b7178" },
    { name: "Classic Brown", hex: "#5c4433" },
    { name: "Rustic Red", hex: "#7a2f2a" },
    { name: "Forest Green", hex: "#2f4a38" },
    { name: "Burnished Slate", hex: "#3f4a52" },
    { name: "Copper Penny", hex: "#a86a3d" },
    { name: "Galvalume Silver", hex: "#c4c8cb" },
  ],
  comparison: {
    title: "Metal Roofing vs. Asphalt Shingles",
    columns: ["Metal Roofing", "Asphalt Shingles"],
    rows: [
      { icon: "clock", feature: "Lifespan", values: ["50+ Years", "15–25 Years"] },
      { icon: "wind", feature: "Wind Resistance", values: ["Up to 140+ MPH", "Up to 60–90 MPH"] },
      { icon: "shield", feature: "Fire Resistance", values: ["Class A (Non-combustible)", "Class A (With Fiberglass Mat)"] },
      { icon: "wrench", feature: "Maintenance", values: ["Low", "Moderate to High"] },
      { icon: "sun", feature: "Energy Efficiency", values: ["High (Reflective)", "Low to Moderate"] },
      { icon: "leaf", feature: "Recyclability", values: ["100% Recyclable", "Limited"] },
      { icon: "dollar", feature: "Return on Investment", values: ["Excellent", "Good"] },
    ],
  },
  processTitle: "Our Metal Roofing Installation Process",
  processIntro: "Expert installation for maximum performance and longevity.",
  process: [
    { n: 1, icon: "search", title: "Inspection", desc: "We evaluate your roof and recommend the best metal system." },
    { n: 2, icon: "wrench", title: "Preparation", desc: "We remove old materials and inspect the deck." },
    { n: 3, icon: "layers", title: "Underlayment", desc: "High-performance underlayment for added protection." },
    { n: 4, icon: "hammer", title: "Installation", desc: "Precision installation of your metal roofing system." },
    { n: 5, icon: "badge", title: "Quality Check", desc: "We inspect every detail for lasting performance." },
    { n: 6, icon: "home", title: "Final Walkthrough", desc: "We ensure your complete satisfaction and clean the site." },
  ],
  warranty: {
    title: "Strong Warranties. Total Peace Of Mind.",
    text: "We offer industry-leading warranties that protect your home and your investment for decades.",
    tiers: [
      { years: "Up to 50 Years", label: "Material Warranty" },
      { years: "Up to 25 Years", label: "Paint Warranty" },
      { years: "Up to 25 Years", label: "Workmanship Warranty" },
    ],
  },
  projectsHeading: "Recent Metal Roofing Projects",
  projects: [img("1576941089067-2de3c901e126"), img("1568605114967-8130f3a36994"), img("1580587771525-78b9dba3b914")],
  review: {
    name: "Eric M.",
    city: "Kirkland, WA",
    initials: "EM",
    quote: "Skyve installed a standing seam metal roof on our home and the difference is incredible. The quality, attention to detail, and crew were top-notch from start to finish!",
  },
  ctaTitle: "Ready To Upgrade To Metal?",
  ctaSubtitle: "Get unmatched durability, energy efficiency, and style with a metal roof from Skyve Roofing.",
  ctaTrust: [
    { icon: "badge", label: "No Obligation Estimate" },
    { icon: "zap", label: "Fast & Easy Process" },
    { icon: "mappin", label: "Local Metal Roofing Experts" },
  ],
};

export const STANDING_SEAM: MaterialPage = {
  slug: "standing-seam-roofing",
  eyebrow: "Standing Seam Roofing",
  titleLines: ["Timeless Strength.", "Modern Performance."],
  sub: "Standing seam metal roofing offers unmatched durability, exceptional weather resistance, and clean, modern lines that elevate any home.",
  heroImage: img("1576941089067-2de3c901e126"),
  whyCard: {
    title: "Why Standing Seam?",
    items: [
      "50+ Year Lifespan",
      "Superior Weather Protection",
      "Concealed Fasteners",
      "Clean, Modern Aesthetic",
      "Low Maintenance",
      "Energy Efficient",
      "Fire & Impact Resistant",
      "Increases Home Value",
    ],
  },
  brandsHeading: "We Install Premium Standing Seam Systems From Industry Leaders",
  brands: ["McElroy Metal", "ATAS", "PAC-CLAD", "Metal Sales", "Fabral", "DynaClad"],
  features: [
    { title: "Exceptional Durability", desc: "Standing seam systems are engineered to withstand the toughest conditions for decades.", checklist: ["Up to 140+ MPH wind resistance", "Heavy snow and ice protection", "Fire & impact resistant", "Resists cracking, shrinking & erosion"], image: img("1576941089067-2de3c901e126") },
    { title: "Built For Performance", desc: "Concealed fasteners and raised seams provide superior leak resistance and thermal performance.", checklist: ["Concealed fastener system", "Thermal movement friendly", "Prevents water infiltration", "Ideal for all climates"], image: img("1568605114967-8130f3a36994") },
    { title: "Modern, Clean Aesthetic", desc: "Sleek vertical lines and hidden fasteners create a timeless look that enhances any architecture.", checklist: ["Clean, uninterrupted lines", "Multiple panel widths", "Premium color options", "Boosts curb appeal & value"], image: img("1583608205776-bfd35f0d9f83") },
  ],
  typesHeading: "Standing Seam Profile Options",
  types: [
    { title: "Classic 1\" Mechanical Lock", desc: "The industry standard for performance and value.", checklist: ["1\" seam height", "Mechanical lock system", "Excellent for most applications", "Proven performance"], image: img("1576941089067-2de3c901e126") },
    { title: "1.5\" Mechanical Lock", desc: "Higher seam for enhanced water protection and bold look.", checklist: ["1.5\" seam height", "Superior water management", "Striking shadow lines", "Ideal for high-end homes"], image: img("1568605114967-8130f3a36994") },
    { title: "2\" Mechanical Lock", desc: "Maximum performance with a tall, dramatic profile.", checklist: ["2\" seam height", "Excellent for heavy rain & snow", "Bold architectural statement", "Ultimate durability"], image: img("1572120360610-d971b9d7767c") },
    { title: "Snap Lock", desc: "Cost-effective snap together panel system.", checklist: ["Concealed clip system", "Fast installation", "Clean appearance", "Great for residential projects"], image: img("1583608205776-bfd35f0d9f83") },
    { title: "Narrow Rib", desc: "Subtle, fine lines for a contemporary appearance.", checklist: ["Narrow rib design", "Modern, minimal look", "Wide coverage", "Ideal for modern homes"], image: img("1600585154340-be6161a56a0c") },
  ],
  colorsHeading: "Popular Standing Seam Colors",
  colorsNote: "Custom colors available. Ask about specialty finishes and coatings.",
  colors: [
    { name: "Matte Black", hex: "#26282b" },
    { name: "Charcoal Gray", hex: "#4a4d50" },
    { name: "Slate Gray", hex: "#6b7178" },
    { name: "Medium Bronze", hex: "#6e5843" },
    { name: "Dark Bronze", hex: "#4a3b2f" },
    { name: "Forest Green", hex: "#2f4a38" },
    { name: "Burgundy", hex: "#6b2434" },
    { name: "Galvalume Silver", hex: "#c4c8cb" },
    { name: "Bone White", hex: "#e8e4da" },
  ],
  comparison: {
    title: "Standing Seam vs. Other Roofing Materials",
    columns: ["Standing Seam Metal", "Asphalt Shingles", "Tile", "Wood Shake"],
    rows: [
      { icon: "clock", feature: "Lifespan", values: ["50+ Years", "15–25 Years", "50+ Years", "30–40 Years"] },
      { icon: "wind", feature: "Wind Resistance", values: ["Up to 140+ MPH", "Up to 60 MPH", "Up to 110 MPH", "Up to 80 MPH"] },
      { icon: "wrench", feature: "Maintenance", values: ["Very Low", "Moderate to High", "Low", "High"] },
      { icon: "shield", feature: "Fire Resistance", values: ["Class A (Non-combustible)", "Class A", "Class A", "Class C"] },
      { icon: "sun", feature: "Energy Efficiency", values: ["Excellent", "Fair", "Good", "Fair"] },
      { icon: "leaf", feature: "Recyclability", values: ["100% Recyclable", "Low", "Natural", "Biodegradable"] },
      { icon: "dollar", feature: "Return on Investment", values: ["Excellent", "Good", "Good", "Moderate"] },
    ],
  },
  processTitle: "Our Installation Process",
  processIntro: "Precision installation for maximum performance and longevity.",
  process: [
    { n: 1, icon: "search", title: "Inspection", desc: "We evaluate your roof and recommend the best solution." },
    { n: 2, icon: "wrench", title: "Preparation", desc: "We remove old materials and inspect the roof deck." },
    { n: 3, icon: "layers", title: "Underlayment", desc: "High-performance underlayment for added protection." },
    { n: 4, icon: "hammer", title: "Panel Installation", desc: "Expert installation of standing seam metal panels." },
    { n: 5, icon: "badge", title: "Quality Check", desc: "We inspect every detail for lasting performance." },
    { n: 6, icon: "home", title: "Final Walkthrough", desc: "We ensure your complete satisfaction and clean the site." },
  ],
  warranty: {
    title: "Industry-Leading Warranties. Total Peace Of Mind.",
    text: "Our standing seam metal roofing systems are backed by some of the best warranties in the industry.",
    tiers: [
      { years: "Up to 50 Years", label: "Material Warranty" },
      { years: "Up to 35 Years", label: "Paint Warranty" },
      { years: "Up to 35 Years", label: "Workmanship Warranty" },
    ],
  },
  projectsHeading: "Recent Standing Seam Projects",
  projects: [img("1576941089067-2de3c901e126"), img("1568605114967-8130f3a36994"), img("1580587771525-78b9dba3b914")],
  review: {
    name: "Sarah M.",
    city: "Sammamish, WA",
    initials: "SM",
    quote: "We chose standing seam for its durability and modern look. The team at Skyve Roofing did an incredible job. Our roof looks amazing and we know it will last for decades!",
  },
  ctaTitle: "Built To Last. Designed To Impress.",
  ctaSubtitle: "Upgrade to standing seam metal roofing and enjoy the perfect combination of strength, beauty, and value.",
  ctaTrust: [
    { icon: "badge", label: "No Obligation Estimate" },
    { icon: "zap", label: "Fast & Easy Process" },
    { icon: "mappin", label: "Local Metal Roofing Experts" },
  ],
};

export const CEDAR_SHAKE: MaterialPage = {
  slug: "cedar-shake-roofing",
  eyebrow: "Cedar Shake Roofing",
  titleLines: ["Natural Beauty.", "Timeless Protection.", "Lasting Value."],
  sub: "Cedar shake roofing delivers unmatched curb appeal and exceptional longevity. A premium choice for homeowners who value craftsmanship, tradition, and performance.",
  heroImage: img("1572120360610-d971b9d7767c"),
  whyCard: {
    title: "Why Cedar Shake?",
    items: [
      "Unmatched natural beauty",
      "Extremely durable & long lasting",
      "Excellent insulation properties",
      "Environmentally sustainable",
      "Increases home value",
      "A premium, timeless investment",
    ],
  },
  brandsHeading: "We Install Premium Cedar Shake Roofing From Trusted Sources",
  brands: ["CertainTeed", "Boralex", "Pacific Cedar Products", "Western Red Cedar", "Malarkey", "Allura"],
  features: [
    { title: "Naturally Beautiful", desc: "Each cedar shake is unique, adding warmth, character, and a distinct look that enhances any architectural style.", checklist: ["Rich, natural wood grain", "Ages beautifully over time", "Enhances curb appeal", "Customizable look and texture"], image: img("1572120360610-d971b9d7767c") },
    { title: "Built To Perform", desc: "Cedar shake roofs are proven to withstand the elements for decades with proper installation and maintenance.", checklist: ["Wind resistant up to 130 MPH+", "Impact & fire resistant when treated", "Excellent insulation & breathability", "Durable in harsh climates"], image: img("1583608205776-bfd35f0d9f83") },
    { title: "Sustainable & Responsible", desc: "Cedar is a renewable resource, and our products come from responsibly managed forests.", checklist: ["100% natural & biodegradable", "Low environmental impact", "Sustainably sourced options", "Supports forest stewardship"], image: img("1531971589569-0d9370cbe1e5") },
  ],
  typesHeading: "Cedar Shake Profile Options",
  types: [
    { title: "Tapersawn Shake", desc: "Hand-split for a thick, rustic look and exceptional durability.", checklist: ["Thick & heavy", "Deep shadow lines", "Premium, rustic appearance", "Longest lifespan"], image: img("1572120360610-d971b9d7767c") },
    { title: "Hand-Split Shake", desc: "Rough-sawn and hand-split for a traditional, natural look.", checklist: ["Natural texture", "Excellent durability", "Classic handcrafted appeal", "Great for high-end homes"], image: img("1583608205776-bfd35f0d9f83") },
    { title: "Resawn Shake", desc: "Precision cut for uniformity and a clean, refined finish.", checklist: ["Consistent thickness", "Smooth surfaces", "Modern, refined appearance", "Balanced performance"], image: img("1568605114967-8130f3a36994") },
    { title: "Perfection Shake®", desc: "Engineered for superior performance with a refined, consistent look.", checklist: ["Engineered for strength", "Class A fire rating available", "Uniform appearance", "Limited lifetime warranty"], image: img("1600585154340-be6161a56a0c") },
    { title: "Treated Shake", desc: "Pressure-treated for enhanced resistance to moisture and decay.", checklist: ["Increased longevity", "Resists rot & insects", "Ideal for wet climates", "Added peace of mind"], image: img("1576941089067-2de3c901e126") },
  ],
  colorsHeading: "Popular Cedar Colors",
  colors: [
    { name: "Natural (Weathered)", hex: "#a07d54" },
    { name: "Light Brown", hex: "#9a7550" },
    { name: "Warm Honey", hex: "#b07b3e" },
    { name: "Rich Cedar", hex: "#8a4f2c" },
    { name: "Rustic Blend", hex: "#7a5638" },
    { name: "Charcoal", hex: "#3a3d40" },
    { name: "Weathered Gray", hex: "#6b6f72" },
    { name: "Custom Stain", hex: "#5c4433" },
  ],
  comparison: {
    title: "Cedar Shake vs. Other Roofing Materials",
    columns: ["Cedar Shake", "Asphalt Shingles", "Metal Roofing"],
    rows: [
      { icon: "clock", feature: "Lifespan", values: ["30–50+ Years", "15–25 Years", "40–70 Years"] },
      { icon: "star", feature: "Natural Beauty", values: ["Excellent", "Good", "Fair"] },
      { icon: "home", feature: "Insulation", values: ["Excellent", "Good", "Fair"] },
      { icon: "wind", feature: "Wind Resistance", values: ["Up to 130 MPH", "Up to 110 MPH", "Up to 140 MPH"] },
      { icon: "shield", feature: "Fire Resistance", values: ["Class B / Class A (with treatment)", "Class A", "Class A"] },
      { icon: "wrench", feature: "Maintenance", values: ["Moderate", "Low", "Low"] },
      { icon: "leaf", feature: "Environmental Impact", values: ["Renewable & Biodegradable", "Petroleum-Based", "Recyclable"] },
      { icon: "dollar", feature: "Return on Investment", values: ["High", "Moderate", "High"] },
    ],
  },
  processTitle: "Our Installation Process",
  processIntro: "Expert craftsmanship for maximum beauty and longevity.",
  process: [
    { n: 1, icon: "search", title: "Inspection", desc: "We evaluate your roof and recommend the best solution." },
    { n: 2, icon: "wrench", title: "Deck Prep", desc: "We inspect & prepare the roof deck for proper ventilation." },
    { n: 3, icon: "layers", title: "Underlayment", desc: "High-quality underlayment for added protection." },
    { n: 4, icon: "home", title: "Starter Course", desc: "We install starter courses for a strong foundation." },
    { n: 5, icon: "hammer", title: "Shake Installation", desc: "Each shake is installed with precision and care." },
    { n: 6, icon: "badge", title: "Quality Check", desc: "We inspect every detail for lasting performance." },
    { n: 7, icon: "star", title: "Final Walkthrough", desc: "We ensure your complete satisfaction and clean the site." },
  ],
  warranty: {
    title: "Industry-Leading Warranties. Total Peace Of Mind.",
    text: "Our cedar shake roofs are backed by some of the best warranties in the industry.",
    tiers: [
      { years: "30-50+ Year", label: "Product Warranty" },
      { years: "15-25 Year", label: "Workmanship Warranty" },
      { years: "Class B / Class A", label: "Fire Rating Available" },
    ],
  },
  projectsHeading: "Recent Cedar Shake Roofing Projects",
  projects: [img("1572120360610-d971b9d7767c"), img("1583608205776-bfd35f0d9f83"), img("1568605114967-8130f3a36994")],
  review: {
    name: "Jason M.",
    city: "Sammamish, WA",
    initials: "JM",
    quote: "Skyve installed a beautiful cedar shake roof on our home. The craftsmanship and attention to detail were outstanding. We couldn't be happier!",
  },
  ctaTitle: "Experience The Beauty Of Cedar Shake Roofing.",
  ctaSubtitle: "A timeless investment that adds value, character, and protection to your home.",
  ctaTrust: [
    { icon: "badge", label: "No Obligation Estimate" },
    { icon: "zap", label: "Fast & Easy Process" },
    { icon: "mappin", label: "Local Roofing Experts" },
  ],
};

export const SYNTHETIC_SHAKE: MaterialPage = {
  slug: "synthetic-shake-roofing",
  eyebrow: "Synthetic Shake Roofing",
  titleLines: ["The Beauty Of Cedar.", "The Performance Of Innovation."],
  sub: "Synthetic shake roofing delivers the authentic look of cedar with advanced materials that provide superior durability, lightweight performance, and virtually no maintenance.",
  heroImage: img("1572120360610-d971b9d7767c"),
  whyCard: {
    title: "Why Synthetic Shake?",
    items: [
      "Authentic cedar appearance",
      "Extreme durability & impact resistant",
      "Lightweight & easy to install",
      "Fire, wind & hail resistant",
      "No rot, mold or insect damage",
      "Low maintenance for life",
      "Sustainable & eco-friendly",
      "Excellent warranty protection",
    ],
  },
  brandsHeading: "We Install Premium Synthetic Shake Roofing From Leading Manufacturers",
  brands: ["Brava Roof Tile", "DaVinci Roofscapes", "Majestic", "Eagle Roofing Products", "CedarRoof by TRI"],
  features: [
    { title: "Designed To Impress", desc: "Advanced manufacturing creates stunning wood shake textures with incredible detail and depth.", checklist: ["Realistic wood grain & shadow lines", "Multiple width options", "Rich, natural color blends", "Enhances curb appeal instantly"], image: img("1572120360610-d971b9d7767c") },
    { title: "Built To Outperform", desc: "Engineered polymer materials withstand the harshest conditions without compromise.", checklist: ["Class 4 Impact Rating (highest)", "Up to 130 MPH wind resistance", "Fire resistant (Class A rated)", "Won't crack, curl or split"], image: img("1583608205776-bfd35f0d9f83") },
    { title: "Smart Long-Term Choice", desc: "Lower lifetime cost with minimal maintenance and exceptional warranty coverage.", checklist: ["50+ year limited warranty", "No treatments or sealants needed", "Resistant to algae & UV fading", "100% recyclable at end of life"], image: img("1568605114967-8130f3a36994") },
  ],
  typesHeading: "Synthetic Shake Style Options",
  types: [
    { title: "Cedar Shake", desc: "Classic hand-split cedar look with varied widths and deep texture.", checklist: ["8\" to 12\" widths", "Staggered edges", "Deep shadow lines", "Traditional appearance"], image: img("1572120360610-d971b9d7767c") },
    { title: "Cedar Shake (Wide)", desc: "Wider profile for bold shadows and dramatic dimension.", checklist: ["12\" to 18\" widths", "Enhanced depth", "Rugged cedar look", "Architectural impact"], image: img("1583608205776-bfd35f0d9f83") },
    { title: "Straight Edge Shake", desc: "Clean, uniform edges for a refined, tailored appearance.", checklist: ["Even, straight edges", "Thicker butt", "Contemporary look", "Clean lines"], image: img("1568605114967-8130f3a36994") },
    { title: "Hand-Split Shake", desc: "Maximum texture and irregular edges for authentic charm.", checklist: ["Random thickness", "Irregular edges", "Old-world character", "Natural variation"], image: img("1600585154340-be6161a56a0c") },
    { title: "Slate Shake", desc: "Combines shake texture with the strength of slate.", checklist: ["Slate-like appearance", "Maximum durability", "Heavyweight look", "Premium option"], image: img("1576941089067-2de3c901e126") },
  ],
  colorsHeading: "Popular Synthetic Shake Colors",
  colorsNote: "Colors may vary by manufacturer. Ask about custom blend options.",
  colors: [
    { name: "Weathered Cedar", hex: "#8a6a45" },
    { name: "Natural Cedar", hex: "#a07d54" },
    { name: "Sunset Blend", hex: "#9a5a34" },
    { name: "Mountain Sage", hex: "#6b6f5a" },
    { name: "Charcoal Gray", hex: "#4a4d50" },
    { name: "Slate Black", hex: "#2a2c2f" },
    { name: "Brownstone", hex: "#6e4b34" },
    { name: "Driftwood", hex: "#9a8b76" },
    { name: "Autumn Blends", hex: "#7a4b2c" },
  ],
  comparison: {
    title: "Synthetic Shake vs. Cedar Shake",
    columns: ["Synthetic Shake", "Cedar Shake"],
    rows: [
      { icon: "clock", feature: "Lifespan", values: ["50+ Years", "20–30 Years"] },
      { icon: "wrench", feature: "Maintenance", values: ["Minimal / None", "High (Staining & Sealing)"] },
      { icon: "droplet", feature: "Rot, Mold, Insects", values: ["Resistant", "Vulnerable"] },
      { icon: "shield", feature: "Fire Rating", values: ["Class A", "Varies (Untreated is Class C)"] },
      { icon: "star", feature: "Impact Resistance", values: ["Class 4 (Highest)", "Low"] },
      { icon: "layers", feature: "Weight (per sq.)", values: ["220–300 lbs", "600–800 lbs"] },
      { icon: "hammer", feature: "Installation", values: ["Faster & Easier", "More Labor Intensive"] },
      { icon: "dollar", feature: "Long-Term Value", values: ["Higher ROI", "Lower ROI"] },
    ],
  },
  processTitle: "Our Installation Process",
  processIntro: "Expert installation ensures maximum performance and longevity.",
  process: [
    { n: 1, icon: "search", title: "Inspection", desc: "We evaluate your roof and recommend the best solution." },
    { n: 2, icon: "wrench", title: "Deck Prep", desc: "We inspect & prepare the deck for proper installation." },
    { n: 3, icon: "layers", title: "Underlayment", desc: "High-performance underlayment for added protection." },
    { n: 4, icon: "hammer", title: "Shake Installation", desc: "Precision installation with proper nailing pattern." },
    { n: 5, icon: "badge", title: "Quality Check", desc: "We inspect every detail for lasting performance." },
    { n: 6, icon: "home", title: "Final Walkthrough", desc: "We ensure your complete satisfaction and clean the site." },
  ],
  warranty: {
    title: "Industry-Leading Warranties. Total Peace Of Mind.",
    text: "Our synthetic shake products are backed by some of the best warranties in the industry.",
    tiers: [
      { years: "50+ Year", label: "Material Warranty" },
      { years: "15 Year", label: "Wind Warranty" },
      { years: "Class 4 Impact", label: "Resistance" },
      { years: "Fire Rated", label: "Class A" },
    ],
  },
  projectsHeading: "Recent Synthetic Shake Projects",
  projects: [img("1572120360610-d971b9d7767c"), img("1583608205776-bfd35f0d9f83"), img("1568605114967-8130f3a36994")],
  review: {
    name: "Jennifer L.",
    city: "Bellevue, WA",
    initials: "JL",
    quote: "We love the look of our new synthetic shake roof! It looks like real cedar but without the constant maintenance. Skyve did an amazing job!",
  },
  ctaTitle: "Get The Cedar Shake Look. Built To Last.",
  ctaSubtitle: "Enjoy timeless beauty with modern performance and protection that lasts for generations.",
  ctaTrust: [
    { icon: "badge", label: "No Obligation Estimate" },
    { icon: "zap", label: "Fast & Easy Process" },
    { icon: "mappin", label: "Local Roofing Experts" },
  ],
};

export const SIDING_REPLACEMENT: MaterialPage = {
  slug: "siding-replacement",
  eyebrow: "Siding Replacement",
  breadcrumbParent: { label: "Exterior Services", href: "/services" },
  titleLines: ["New Look. Better Protection.", "Stronger Value."],
  sub: "Siding replacement instantly enhances your home's beauty, improves energy efficiency, and provides long-lasting protection against the elements.",
  heroImage: img("1605146769289-440113cc3d00"),
  whyCard: {
    title: "Why Replace Your Siding?",
    items: [
      "Boost curb appeal and home value",
      "Improve energy efficiency",
      "Protect against moisture and weather",
      "Reduce maintenance and repairs",
      "Increase durability and longevity",
      "Choose from a wide range of styles",
      "Professional installation guaranteed",
    ],
  },
  brandsHeading: "We Install Premium Siding From Trusted Brands",
  brands: ["James Hardie", "LP Building Solutions", "CertainTeed", "Mastic by Ply Gem", "Royal Building Products", "KWP"],
  features: [
    { icon: "home", title: "Transform Your Home", desc: "New siding refreshes your home's appearance and makes it stand out in the neighborhood.", checklist: ["Increase home value", "Modernize your style", "Wide variety of colors", "Beautiful, long-lasting finish"], image: img("1605146769289-440113cc3d00") },
    { icon: "zap", title: "Energy Efficiency", desc: "Insulated siding options help reduce heating and cooling costs year-round.", checklist: ["Better insulation", "Lower energy bills", "More comfortable home", "ENERGY STAR® options"], image: img("1564013799919-ab600027ffc6") },
    { icon: "shield", title: "Built To Protect", desc: "Quality siding shields your home from wind, rain, hail, and extreme weather.", checklist: ["Moisture resistant", "Won't warp or crack", "Fade and impact resistant", "Built for any climate"], image: img("1605276374104-dee2a0ed3cd6") },
    { icon: "wrench", title: "Low Maintenance", desc: "Modern siding materials are designed for durability with minimal upkeep.", checklist: ["Easy to clean", "No painting required", "Resists rot and pests", "Lasts for decades"], image: img("1583608205776-bfd35f0d9f83") },
  ],
  typesHeading: "Siding Material Options",
  types: [
    { title: "Fiber Cement Siding", desc: "Extremely durable and resistant to fire, rot, pests, and extreme weather.", checklist: ["25–50 year lifespan", "Fire resistant", "Wood-like look", "Low maintenance"], image: img("1605146769289-440113cc3d00") },
    { title: "Vinyl Siding", desc: "Affordable, versatile, and available in many colors and styles.", checklist: ["Cost-effective", "Low maintenance", "Fade resistant", "Insulated options"], image: img("1605276374104-dee2a0ed3cd6") },
    { title: "Engineered Wood Siding", desc: "Real wood beauty with enhanced durability and weather resistance.", checklist: ["Natural wood look", "Enhanced durability", "Resists warping", "Sustainably sourced"], image: img("1572120360610-d971b9d7767c") },
    { title: "Insulated Siding", desc: "Built-in insulation for improved energy efficiency and comfort.", checklist: ["Better R-value", "Lower energy bills", "Quieter indoors", "Year-round comfort"], image: img("1564013799919-ab600027ffc6") },
    { title: "Metal Siding", desc: "Modern look with exceptional durability and fire resistance.", checklist: ["Fire resistant", "Recyclable", "Low maintenance", "Long lifespan"], image: img("1600585154340-be6161a56a0c") },
    { title: "Shake & Shingle Siding", desc: "Timeless style that adds charm and dimension to any home.", checklist: ["Classic appearance", "Great curb appeal", "Variety of styles", "Premium look"], image: img("1583608205776-bfd35f0d9f83") },
  ],
  colorsHeading: "Popular Siding Colors",
  colors: [
    { name: "Arctic White", hex: "#f0f0ec" },
    { name: "Cobblestone", hex: "#c9c2b4" },
    { name: "Pearl Gray", hex: "#cccdcd" },
    { name: "Monterey Taupe", hex: "#b0a48f" },
    { name: "Woodland Cream", hex: "#e0d3b0" },
    { name: "Navy Blue", hex: "#2a3546" },
    { name: "Iron Gray", hex: "#5a5f63" },
    { name: "Deep Moss", hex: "#4a5540" },
  ],
  comparison: {
    title: "Siding vs. Other Exterior Options",
    columns: ["Siding", "Paint", "Stucco", "Brick"],
    rows: [
      { icon: "shield", feature: "Durability", values: ["High", "Low", "Medium", "Very High"] },
      { icon: "wrench", feature: "Maintenance", values: ["Low", "High", "Medium", "Low"] },
      { icon: "zap", feature: "Energy Efficiency", values: ["High (with insulation)", "Low", "Medium", "Medium"] },
      { icon: "dollar", feature: "Cost", values: ["Moderate", "Low", "High", "High"] },
      { icon: "star", feature: "Variety of Styles", values: ["Excellent", "Good", "Good", "Limited"] },
      { icon: "clock", feature: "Installation Time", values: ["Moderate", "Low", "High", "High"] },
      { icon: "chart", feature: "Return on Investment", values: ["High", "Low", "Medium", "High"] },
    ],
  },
  processTitle: "Our Siding Replacement Process",
  processIntro: "A proven process for exceptional results and a stress-free experience.",
  process: [
    { n: 1, icon: "search", title: "Inspection", desc: "We assess your current siding and recommend the best solution." },
    { n: 2, icon: "layers", title: "Material Selection", desc: "We help you choose the perfect style, color, and material." },
    { n: 3, icon: "wrench", title: "Preparation", desc: "We remove old siding and prepare your home." },
    { n: 4, icon: "hammer", title: "Professional Installation", desc: "Our experts install your new siding with precision." },
    { n: 5, icon: "badge", title: "Quality Check", desc: "We inspect every detail to ensure perfection." },
    { n: 6, icon: "trash", title: "Clean Up", desc: "We leave your home clean and beautiful." },
    { n: 7, icon: "home", title: "Final Walkthrough", desc: "Your satisfaction is our guarantee." },
  ],
  warranty: {
    title: "Industry-Leading Warranties. Total Peace Of Mind.",
    text: "We stand behind our siding installations with strong warranties from top manufacturers.",
    tiers: [
      { years: "Up to 50 Years", label: "Product Warranty" },
      { years: "Up to 15 Years", label: "Labor Warranty" },
      { years: "Up to 30 Years", label: "Fade Warranty" },
    ],
  },
  projectsHeading: "Recent Siding Replacement Projects",
  projects: [img("1605146769289-440113cc3d00"), img("1605276374104-dee2a0ed3cd6"), img("1564013799919-ab600027ffc6")],
  review: {
    name: "Susan M.",
    city: "Bellevue, WA",
    initials: "SM",
    quote: "Skyve transformed the look of our home with beautiful new siding. The team was professional, on time, and the results are absolutely stunning!",
  },
  ctaTitle: "Upgrade Your Home. Protect Your Investment.",
  ctaSubtitle: "Get expert siding replacement from the trusted exterior specialists at Skyve Roofing & Exteriors.",
  ctaTrust: [
    { icon: "badge", label: "No Obligation Estimate" },
    { icon: "zap", label: "Fast & Easy Process" },
    { icon: "mappin", label: "Local Siding Experts" },
  ],
};

export const TPO_ROOFING: MaterialPage = {
  slug: "tpo-roofing",
  eyebrow: "TPO Roofing",
  titleLines: ["Flat Roof Protection.", "Built To Perform."],
  sub: "TPO roofing systems deliver superior energy efficiency, weather resistance, and long-term performance for flat and low-slope roofs.",
  heroImage: img("1600585154340-be6161a56a0c"),
  whyCard: {
    title: "Why TPO Roofing?",
    items: [
      "Superior energy efficiency",
      "Heat-welded seams for strength",
      "Chemical & puncture resistant",
      "Reflects UV rays",
      "Low maintenance",
      "Cost-effective solution",
      "Ideal for flat & low-slope roofs",
    ],
  },
  brandsHeading: "We Install Premium TPO Roofing Systems From Trusted Brands",
  brands: ["GAF", "Carlisle SynTec", "Firestone", "Duro-Last", "Versico"],
  features: [
    { icon: "sun", title: "Energy Efficient", desc: "TPO's reflective surface reduces heat absorption and lowers cooling costs.", checklist: ["Up to 88% solar reflectivity", "Reduces cooling costs", "ENERGY STAR® compliant", "Helps extend roof life"], image: img("1600585154340-be6161a56a0c") },
    { icon: "shield", title: "Durable & Reliable", desc: "Heat-welded seams create a watertight membrane that lasts.", checklist: ["Heat-welded seams", "Puncture & tear resistant", "Chemical resistant", "Withstands harsh weather"], image: img("1632759145351-1d592919f522") },
    { icon: "dollar", title: "Smart Investment", desc: "Long-term performance with low maintenance and excellent ROI.", checklist: ["Lower lifecycle cost", "Minimal maintenance", "Eligible for warranties up to 30 years", "Great for commercial & residential"], image: img("1600596542815-ffad4c1539a9") },
  ],
  typesHeading: "TPO Membrane Options",
  types: [
    { title: "Mechanically Attached TPO", desc: "Fastened with plates and screws for secure, cost-effective installation.", checklist: ["Strong wind uplift performance", "Fast installation", "Ideal for large roof areas"], image: img("1600585154340-be6161a56a0c") },
    { title: "Fully Adhered TPO", desc: "Adhered directly to the deck for maximum wind uplift resistance.", checklist: ["Superior wind uplift resistance", "No membrane movement", "Ideal for high wind zones"], image: img("1600596542815-ffad4c1539a9") },
    { title: "Ballasted TPO", desc: "Installed with ballast (rock or pavers) to hold the membrane in place.", checklist: ["No penetration required", "Ideal for retrofit projects", "Easy to maintain & repair"], image: img("1502005229762-cf1b2da7c5d6") },
    { title: "Self-Adhered TPO", desc: "Self-adhering backing for quick installation and strong bonding.", checklist: ["Reduced installation time", "Strong adhesion", "Ideal for cold weather"], image: img("1583608205776-bfd35f0d9f83") },
  ],
  colorsHeading: "Popular TPO Colors",
  colors: [
    { name: "White", hex: "#f4f4f2" },
    { name: "Light Gray", hex: "#d5d6d6" },
    { name: "Tan", hex: "#cbb591" },
    { name: "Sandstone", hex: "#6b6f72" },
    { name: "Slate Gray", hex: "#8a8d8f" },
    { name: "Everguard® Gray", hex: "#a8abad" },
  ],
  comparison: {
    title: "TPO vs. Other Flat Roofing Materials",
    columns: ["TPO Roofing", "EPDM", "PVC"],
    rows: [
      { icon: "sun", feature: "Energy Efficiency", values: ["Excellent (Reflective)", "Good (Dark)", "Excellent (Reflective)"] },
      { icon: "layers", feature: "Heat-Welded Seams", values: ["Yes", "No (Seams Glued)", "Yes"] },
      { icon: "droplet", feature: "Chemical Resistance", values: ["Excellent", "Good", "Excellent"] },
      { icon: "shield", feature: "Puncture Resistance", values: ["High", "Good", "High"] },
      { icon: "clock", feature: "Installation Time", values: ["Fast", "Moderate", "Moderate"] },
      { icon: "badge", feature: "Lifespan", values: ["15–30 Years", "15–25 Years", "20–30 Years"] },
      { icon: "wrench", feature: "Maintenance", values: ["Low", "Moderate", "Low"] },
      { icon: "dollar", feature: "Cost", values: ["Cost-Effective", "Lower Initial Cost", "Higher"] },
    ],
  },
  processTitle: "Our TPO Roofing Installation Process",
  processIntro: "A proven process for long-lasting, high-performance results.",
  process: [
    { n: 1, icon: "search", title: "Inspection", desc: "We evaluate your roof and recommend the best TPO system." },
    { n: 2, icon: "wrench", title: "Deck Prep", desc: "We clean and prepare the deck for optimal adhesion." },
    { n: 3, icon: "layers", title: "Insulation", desc: "High-performance insulation installed for energy efficiency." },
    { n: 4, icon: "hammer", title: "TPO Installation", desc: "Membrane installed and heat-welded at the seams." },
    { n: 5, icon: "badge", title: "Quality Check", desc: "We inspect every detail to ensure perfection." },
    { n: 6, icon: "home", title: "Final Walkthrough", desc: "We ensure your complete satisfaction and clean the site." },
  ],
  warranty: {
    title: "Industry-Leading Warranties. Total Peace Of Mind.",
    text: "We offer premium TPO warranties backed by top manufacturers and expert installation.",
    tiers: [
      { years: "Up to 30 Years", label: "System Warranty" },
      { years: "Up to 20 Years", label: "Materials Warranty" },
      { years: "Up to 15 Years", label: "Workmanship Warranty" },
    ],
  },
  projectsHeading: "Recent TPO Roofing Projects",
  projects: [img("1600585154340-be6161a56a0c"), img("1600596542815-ffad4c1539a9"), img("1502005229762-cf1b2da7c5d6")],
  review: {
    name: "Michael R.",
    city: "Bellevue, WA",
    initials: "MR",
    quote: "Skyve installed a TPO roof on our flat roof and the results are incredible. The team was professional, the process was smooth, and the roof looks amazing!",
  },
  ctaTitle: "Protect Your Flat Roof. Protect Your Building.",
  ctaSubtitle: "Get expert TPO roofing installed by the local roofing experts at Skyve Roofing & Exteriors.",
  ctaTrust: [
    { icon: "badge", label: "No Obligation Estimate" },
    { icon: "zap", label: "Fast & Easy Process" },
    { icon: "mappin", label: "Local Roofing Experts" },
  ],
};

export const PVC_ROOFING: MaterialPage = {
  slug: "pvc-roofing",
  eyebrow: "PVC Roofing",
  titleLines: ["Superior Protection.", "Maximum Performance."],
  sub: "PVC roofing systems deliver exceptional durability, chemical resistance, and energy efficiency for flat and low-slope roofs in any environment.",
  heroImage: img("1600585154340-be6161a56a0c"),
  whyCard: {
    title: "Why PVC Roofing?",
    items: [
      "Exceptional chemical resistance",
      "Superior heat-welded seams",
      "High reflectivity & energy efficiency",
      "Puncture, tear & fire resistant",
      "Low maintenance & long life",
      "Resistant to grease, oils & acids",
      "Ideal for commercial & residential",
    ],
  },
  brandsHeading: "We Install Premium PVC Roofing Systems From Trusted Brands",
  brands: ["Carlisle SynTec", "Duro-Last", "GAF", "Versico", "Firestone"],
  features: [
    { icon: "sun", title: "Energy Efficient", desc: "PVC's bright white surface reflects sunlight and reduces heat absorption, lowering your cooling costs.", checklist: ["Up to 88% solar reflectivity", "ENERGY STAR® compliant", "Reduces rooftop temperature", "Lowers HVAC energy usage"], image: img("1600585154340-be6161a56a0c") },
    { icon: "shield", title: "Unmatched Durability", desc: "Engineered for maximum performance in harsh environments, including exposure to chemicals, oils, and grease.", checklist: ["Superior chemical resistance", "Heat-welded seams for strength", "Puncture & tear resistant", "Withstands extreme weather"], image: img("1632759145351-1d592919f522") },
    { icon: "dollar", title: "Low Maintenance. Long Life.", desc: "PVC roofs require minimal maintenance and offer one of the longest lifespans in the roofing industry.", checklist: ["Low lifecycle cost", "Minimal maintenance", "Eligible for warranties up to 30 years", "100% recyclable at end of life"], image: img("1600596542815-ffad4c1539a9") },
  ],
  typesHeading: "PVC Membrane Options",
  types: [
    { title: "Standard White PVC", desc: "The most popular choice for energy efficiency and cost-effectiveness.", checklist: ["Smooth surface", "High reflectivity", "Heat-weldable seams", "Great for all climates"], image: img("1600585154340-be6161a56a0c") },
    { title: "Tan PVC", desc: "Tan color helps hide dirt and foot traffic for a cleaner appearance.", checklist: ["Lower heat absorption", "Hides dirt & debris", "Heat-weldable seams", "Ideal for high-traffic roofs"], image: img("1502005229762-cf1b2da7c5d6") },
    { title: "Gray PVC", desc: "Great for reducing glare and blending with surrounding structures.", checklist: ["Lower glare", "Clean, modern look", "Heat-weldable seams", "Excellent durability"], image: img("1600596542815-ffad4c1539a9") },
    { title: "Reinforced PVC", desc: "Added reinforcement layer for extra strength in demanding applications.", checklist: ["Superior puncture resistance", "Extra dimensional stability", "Ideal for mechanical attachment", "Extreme durability"], image: img("1583608205776-bfd35f0d9f83") },
  ],
  colorsHeading: "Popular PVC Colors",
  colors: [
    { name: "Bright White", hex: "#f6f6f4" },
    { name: "Tan", hex: "#cbb591" },
    { name: "Light Gray", hex: "#d5d6d6" },
    { name: "Medium Gray", hex: "#6b6f72" },
    { name: "Patina Green", hex: "#6b7a6a" },
  ],
  comparison: {
    title: "PVC vs. Other Flat Roofing Materials",
    columns: ["PVC Roofing", "TPO Roofing", "EPDM Roofing", "Built-Up Roof"],
    rows: [
      { icon: "sun", feature: "Energy Efficiency", values: ["Excellent (Reflective)", "Excellent", "Good", "Poor"] },
      { icon: "layers", feature: "Heat-Welded Seams", values: ["Yes", "Yes (Heat Air)", "No", "No"] },
      { icon: "droplet", feature: "Chemical Resistance", values: ["Excellent", "Good", "Fair", "Poor"] },
      { icon: "shield", feature: "Puncture Resistance", values: ["Excellent", "Good", "Good", "Good"] },
      { icon: "badge", feature: "Membrane Lifespan", values: ["20–30 Years", "15–20 Years", "15–20 Years", "20–25 Years"] },
      { icon: "wrench", feature: "Maintenance", values: ["Low", "Low", "Low", "High"] },
      { icon: "dollar", feature: "Cost", values: ["Cost-Effective", "Cost-Effective", "Lower Initial Cost", "Higher"] },
    ],
  },
  processTitle: "Our PVC Roofing Installation Process",
  processIntro: "Precision installation for maximum performance and longevity.",
  process: [
    { n: 1, icon: "search", title: "Inspection", desc: "We evaluate your roof and recommend the best PVC solution." },
    { n: 2, icon: "wrench", title: "Deck Prep", desc: "We clean and prepare the deck for optimal membrane adhesion." },
    { n: 3, icon: "layers", title: "Insulation", desc: "High-performance insulation installed for energy efficiency." },
    { n: 4, icon: "hammer", title: "Membrane Installation", desc: "PVC membrane is heat-welded at the seams for strength." },
    { n: 5, icon: "badge", title: "Quality Check", desc: "We inspect every detail for long-lasting performance." },
    { n: 6, icon: "home", title: "Final Walkthrough", desc: "We ensure your complete satisfaction and clean the site." },
  ],
  warranty: {
    title: "Industry-Leading Warranties. Total Peace Of Mind.",
    text: "We offer industry-best PVC warranties backed by top manufacturers and expert installation.",
    tiers: [
      { years: "Up to 30 Years", label: "System Warranty" },
      { years: "Up to 25 Years", label: "Materials Warranty" },
      { years: "Up to 20 Years", label: "Labor Warranty" },
      { years: "Up to 30 Years", label: "Reflectivity Warranty" },
    ],
  },
  projectsHeading: "Recent PVC Roofing Projects",
  projects: [img("1600585154340-be6161a56a0c"), img("1600596542815-ffad4c1539a9"), img("1502005229762-cf1b2da7c5d6")],
  review: {
    name: "David K.",
    city: "Redmond, WA",
    initials: "DK",
    quote: "Skyve installed a PVC roof on our commercial building and we couldn't be happier. The installation was flawless and the team was professional from start to finish.",
  },
  ctaTitle: "Built For Performance. Designed To Last.",
  ctaSubtitle: "Upgrade to PVC roofing and protect your property with a premium roofing system that delivers unmatched performance and efficiency.",
  ctaTrust: [
    { icon: "badge", label: "No Obligation Estimate" },
    { icon: "zap", label: "Fast & Easy Process" },
    { icon: "mappin", label: "Local Roofing Experts" },
  ],
};

export const LOW_SLOPE: MaterialPage = {
  slug: "low-slope-roofing",
  eyebrow: "Low Slope Roofing",
  titleLines: ["Engineered For Performance.", "Built For Protection."],
  sub: "Low slope roofing systems deliver reliable waterproofing, energy efficiency, and long-term durability for commercial, multi-family, and modern residential flat or low-slope roofs.",
  heroImage: img("1600585154340-be6161a56a0c"),
  whyCard: {
    title: "Why Low Slope Systems?",
    items: [
      "Designed for flat & low-slope roofs",
      "Superior waterproofing protection",
      "Energy efficient & reflective",
      "Seamless or heat-welded options",
      "Resistant to ponding water",
      "Long lifespan with low maintenance",
      "Ideal for commercial & residential",
    ],
  },
  brandsHeading: "We Install Premium Low Slope Roofing Systems From Trusted Brands",
  brands: ["GAF", "Carlisle SynTec", "Versico", "Firestone", "Duro-Last", "Johns Manville"],
  features: [
    { icon: "shield", title: "Dependable Waterproofing", desc: "Advanced membrane technology and proper installation keep your building protected for decades.", checklist: ["Heat-welded seams for strength", "Resistant to ponding water", "Superior puncture & tear resistance", "Meets or exceeds industry standards"], image: img("1600585154340-be6161a56a0c") },
    { icon: "sun", title: "Energy Efficient", desc: "Reflective membranes reduce heat absorption and lower cooling costs year-round.", checklist: ["Up to 88% solar reflectivity", "ENERGY STAR® compliant options", "Lower HVAC costs", "Cool roof options available"], image: img("1600596542815-ffad4c1539a9") },
    { icon: "dollar", title: "Cost-Effective & Long-Lasting", desc: "Low maintenance, long lifespan systems that protect your investment.", checklist: ["Minimal maintenance required", "Warranties up to 30 years", "Lower lifecycle cost", "Ideal for new construction or retrofit"], image: img("1502005229762-cf1b2da7c5d6") },
  ],
  typesHeading: "Low Slope Roofing System Options",
  types: [
    { title: "TPO Roofing", desc: "Heat-welded thermoplastic membrane that offers excellent energy efficiency and durability.", checklist: ["Heat-welded seams", "High solar reflectivity", "Chemical resistant", "Ideal for all climates"], image: img("1600585154340-be6161a56a0c") },
    { title: "PVC Roofing", desc: "Superior chemical resistance and long-term performance.", checklist: ["Heat-welded seams", "Fire-resistant options", "Exceptional durability", "Resists grease, oils & chemicals"], image: img("1600596542815-ffad4c1539a9") },
    { title: "EPDM Roofing", desc: "Proven rubber membrane with excellent flexibility and longevity.", checklist: ["Cost-effective solution", "Cold-adhesive options", "Excellent UV resistance", "Flexible in extreme temps"], image: img("1502005229762-cf1b2da7c5d6") },
    { title: "Modified Bitumen", desc: "Multi-ply system with strong protection against foot traffic and punctures.", checklist: ["Torch or cold applied", "High puncture resistance", "Excellent durability", "Great for heavy-traffic roofs"], image: img("1583608205776-bfd35f0d9f83") },
    { title: "Built-Up Roofing (BUR)", desc: "Traditional multi-ply system providing ultimate protection.", checklist: ["Exceptional longevity", "Strong against foot traffic", "Multiple layer protection", "Ideal for large commercial roofs"], image: img("1632759145351-1d592919f522") },
  ],
  colorsHeading: "Popular Low Slope Roofing Colors",
  colors: [
    { name: "White", hex: "#f4f4f2" },
    { name: "Light Gray", hex: "#d5d6d6" },
    { name: "Tan", hex: "#cbb591" },
    { name: "Medium Gray", hex: "#6b6f72" },
    { name: "Dark Gray", hex: "#3f4245" },
    { name: "Slate Gray", hex: "#5a6560" },
  ],
  comparison: {
    title: "Low Slope Roofing vs. Other Roofing Materials",
    columns: ["TPO / PVC", "EPDM", "Modified Bitumen", "BUR"],
    rows: [
      { icon: "sun", feature: "Energy Efficiency", values: ["Excellent (Reflective)", "Good", "Good", "Fair"] },
      { icon: "layers", feature: "Seam Strength", values: ["Heat-Welded", "Adhered", "Sealed Laps", "Hot Mopped"] },
      { icon: "droplet", feature: "Ponding Water Resistance", values: ["Excellent", "Good", "Good", "Excellent"] },
      { icon: "shield", feature: "Chemical Resistance", values: ["Excellent", "Good", "Good", "Fair"] },
      { icon: "clock", feature: "Lifespan", values: ["20–30 Years", "15–25 Years", "15–20 Years", "20–30+ Years"] },
      { icon: "wrench", feature: "Maintenance", values: ["Low", "Low", "Moderate", "High"] },
      { icon: "dollar", feature: "Cost", values: ["Cost-Effective", "Cost-Effective", "Moderate", "Higher"] },
    ],
  },
  processTitle: "Our Low Slope Roofing Process",
  processIntro: "Expert installation for lasting performance and protection.",
  process: [
    { n: 1, icon: "search", title: "Inspection", desc: "We evaluate your roof and recommend the best system." },
    { n: 2, icon: "wrench", title: "Deck Preparation", desc: "We clean and prepare the surface to ensure proper adhesion." },
    { n: 3, icon: "layers", title: "Insulation", desc: "High-performance insulation is installed for energy efficiency." },
    { n: 4, icon: "hammer", title: "Membrane Installation", desc: "Membrane is installed using heat-welded or adhesive methods." },
    { n: 5, icon: "badge", title: "Quality Check", desc: "We inspect every detail for top-quality performance." },
    { n: 6, icon: "home", title: "Final Walkthrough", desc: "We ensure your complete satisfaction and clean the site." },
  ],
  warranty: {
    title: "Industry-Leading Warranties. Total Peace Of Mind.",
    text: "We stand behind our low slope roofing systems with some of the best warranties in the industry.",
    tiers: [
      { years: "Up to 30 Years", label: "System Warranty" },
      { years: "Up to 20 Years", label: "Material Warranty" },
      { years: "Up to 15 Years", label: "Labor Warranty" },
      { years: "Up to 30 Years", label: "Reflectivity Warranty" },
    ],
  },
  projectsHeading: "Recent Low Slope Roofing Projects",
  reviewsHeading: "What Property Owners Are Saying",
  projects: [img("1600585154340-be6161a56a0c"), img("1600596542815-ffad4c1539a9"), img("1502005229762-cf1b2da7c5d6")],
  review: {
    name: "Brian T.",
    city: "Bellevue, WA",
    initials: "BT",
    quote: "Skyve installed a TPO roof on our office building and the difference in temperature and energy costs has been incredible. The crew was professional, fast, and detailed.",
  },
  ctaTitle: "Protect Your Building. Lower Your Costs.",
  ctaSubtitle: "Upgrade to a high-performance low slope roofing system installed by the experts at Skyve Roofing & Exteriors.",
  ctaTrust: [
    { icon: "badge", label: "No Obligation Estimate" },
    { icon: "zap", label: "Fast & Easy Process" },
    { icon: "mappin", label: "Local Roofing Experts" },
  ],
};

export const FIBER_CEMENT: MaterialPage = {
  slug: "fiber-cement-siding",
  eyebrow: "Fiber Cement Siding",
  breadcrumbParent: { label: "Exterior Services", href: "/services" },
  titleLines: ["Beauty. Strength. Built", "to Last for Decades."],
  sub: "Fiber cement siding delivers unmatched durability, fire resistance, and timeless curb appeal with the look of wood — without the wood maintenance.",
  heroImage: img("1605146769289-440113cc3d00"),
  whyCard: {
    title: "Why Choose Fiber Cement Siding?",
    items: [
      "Exceptional durability & strength",
      "Resists fire, rot, insects & moisture",
      "Holds paint better & longer",
      "Low maintenance & easy to clean",
      "Beautiful style & texture options",
      "Adds value & curb appeal",
      "Backed by long-term warranties",
    ],
  },
  brandsHeading: "We Install Premium Fiber Cement Siding From Trusted Brands",
  brands: ["James Hardie", "LP Building Solutions", "CertainTeed", "Equitone"],
  features: [
    { icon: "shield", title: "Unmatched Durability", desc: "Engineered to withstand harsh weather, impacts, and time.", checklist: ["Resists rot, warping & swelling", "Non-combustible & fire resistant", "Holds up in extreme climates", "Impact & hail resistant"], image: img("1605146769289-440113cc3d00") },
    { icon: "star", title: "Timeless Beauty", desc: "Get the look you love with a variety of styles and textures.", checklist: ["Looks like real wood", "Wide range of colors", "Smooth, woodgrain & textured finishes", "Enhances any architectural style"], image: img("1564013799919-ab600027ffc6") },
    { icon: "wrench", title: "Low Maintenance", desc: "Spend less time maintaining your home and more time enjoying it.", checklist: ["Won't peel, rot or crack", "No frequent painting", "Easy to clean", "Built to last for decades"], image: img("1605276374104-dee2a0ed3cd6") },
    { icon: "dollar", title: "Smart Investment", desc: "Long-term performance and beauty that adds value to your home.", checklist: ["Increases property value", "Lower lifetime costs", "Backed by strong warranties", "Trusted by homeowners"], image: img("1583608205776-bfd35f0d9f83") },
  ],
  typesHeading: "Fiber Cement Siding Styles",
  types: [
    { title: "Lap Siding (Plank)", desc: "The most popular choice. Classic horizontal boards for a clean, traditional look.", checklist: ["Versatile & timeless", "Wide exposure options", "Smooth or woodgrain"], image: img("1605146769289-440113cc3d00") },
    { title: "Board & Batten", desc: "Bold vertical panels for a modern farmhouse or rustic look.", checklist: ["Strong vertical lines", "Adds depth & character", "Great for gables & accents"], image: img("1605276374104-dee2a0ed3cd6") },
    { title: "Shingle Siding", desc: "Cedar shake look with the strength of fiber cement.", checklist: ["Hand-split or straight edge", "Traditional charm", "Great for accents"], image: img("1572120360610-d971b9d7767c") },
    { title: "Panel Siding", desc: "Large format panels for a sleek, modern appearance.", checklist: ["Clean, contemporary lines", "Fewer seams", "Smooth or textured"], image: img("1600585154340-be6161a56a0c") },
    { title: "Trim & Soffit", desc: "Complete the look with durable trim, soffit, and fascia options.", checklist: ["Moisture & rot resistant", "Pre-finished options", "Perfect finishing touch"], image: img("1564013799919-ab600027ffc6") },
  ],
  colorsHeading: "Popular Fiber Cement Colors",
  colors: [
    { name: "Arctic White", hex: "#f0f0ec" },
    { name: "Cobblestone", hex: "#c9c2b4" },
    { name: "Pearl Gray", hex: "#cccdcd" },
    { name: "Monterey Taupe", hex: "#b0a48f" },
    { name: "Evening Blue", hex: "#2a3546" },
    { name: "Iron Gray", hex: "#5a5f63" },
    { name: "Mountain Sage", hex: "#6b7358" },
    { name: "Rich Espresso", hex: "#3f2f26" },
  ],
  comparison: {
    title: "Fiber Cement Siding vs. Other Siding Materials",
    columns: ["Fiber Cement", "Vinyl", "Wood", "Aluminum"],
    rows: [
      { icon: "shield", feature: "Durability", values: ["Excellent", "Good", "Fair", "Good"] },
      { icon: "badge", feature: "Fire Resistance", values: ["Non-Combustible", "Low", "Low", "Low"] },
      { icon: "droplet", feature: "Rot & Insect Resistance", values: ["Excellent", "Excellent", "Poor", "Excellent"] },
      { icon: "wrench", feature: "Maintenance", values: ["Low", "Very Low", "High", "Low"] },
      { icon: "star", feature: "Paint Hold & Finish", values: ["Excellent", "Good", "Poor", "Good"] },
      { icon: "clock", feature: "Lifespan", values: ["30–50+ Years", "20–30 Years", "10–20 Years", "20–40 Years"] },
      { icon: "dollar", feature: "Return on Investment", values: ["High", "Moderate", "Low", "Moderate"] },
    ],
  },
  processTitle: "Our Fiber Cement Siding Installation Process",
  processIntro: "Expert installation for a flawless finish and long-lasting performance.",
  process: [
    { n: 1, icon: "search", title: "Inspection", desc: "We assess your home and recommend the best solution." },
    { n: 2, icon: "layers", title: "Material Selection", desc: "We help you choose the perfect style, color, and trim." },
    { n: 3, icon: "wrench", title: "Preparation", desc: "We prepare your home for a clean installation." },
    { n: 4, icon: "hammer", title: "Professional Installation", desc: "Our experts install with precision and attention to detail." },
    { n: 5, icon: "badge", title: "Final Inspection", desc: "We ensure every detail meets our high standards." },
    { n: 6, icon: "trash", title: "Cleanup", desc: "We leave your property spotless and beautiful." },
  ],
  warranty: {
    title: "Industry-Leading Warranties. Total Peace Of Mind.",
    text: "We stand behind our work and the products we install with strong, transferable warranties.",
    tiers: [
      { years: "Up to 30 Years", label: "Product Warranty" },
      { years: "Up to 15 Years", label: "Color Warranty" },
      { years: "Up to 15 Years", label: "Finish Warranty" },
      { years: "Up to 10 Years", label: "Labor Warranty" },
    ],
  },
  projectsHeading: "Recent Fiber Cement Siding Projects",
  projects: [img("1605146769289-440113cc3d00"), img("1605276374104-dee2a0ed3cd6"), img("1564013799919-ab600027ffc6")],
  review: {
    name: "Mark T.",
    city: "Sammamish, WA",
    initials: "MT",
    quote: "Skyve did an amazing job on our fiber cement siding. The crew was professional, the communication was great, and the results exceeded our expectations!",
  },
  ctaTitle: "Stronger. Smarter. More Beautiful.",
  ctaSubtitle: "Upgrade to fiber cement siding and enjoy lasting protection with timeless style.",
  ctaTrust: [
    { icon: "badge", label: "No Obligation Estimate" },
    { icon: "zap", label: "Fast & Easy Process" },
    { icon: "mappin", label: "Local Siding Experts" },
  ],
};

export const EXTERIOR_PAINTING: MaterialPage = {
  slug: "exterior-painting",
  eyebrow: "Exterior Painting",
  breadcrumbParent: { label: "Exterior Services", href: "/services" },
  titleLines: ["Transform Your Home.", "Protect What Matters."],
  sub: "Professional exterior painting enhances curb appeal, protects your home from the elements, and increases property value with a beautiful, long-lasting finish.",
  heroImage: img("1605146769289-440113cc3d00"),
  whyCard: {
    title: "Why Paint With Skyve?",
    items: [
      "Premium paints & materials",
      "Expert prep for lasting results",
      "Weather-resistant protection",
      "Increase curb appeal & value",
      "Detailed, clean & on-time crews",
      "Color consultation included",
      "Satisfaction guaranteed",
    ],
  },
  brandsHeading: "We Use Premium Paints From Trusted Brands",
  brands: ["Sherwin-Williams", "Benjamin Moore", "Pittsburgh Paints", "Behr", "PPG"],
  features: [
    { icon: "star", title: "Beautiful Results", desc: "Expert color & finish application for a stunning curb appeal.", checklist: ["Smooth, even finishes", "Precise trim & detail work", "Color consultation included", "Many colors & styles"], image: img("1605146769289-440113cc3d00") },
    { icon: "shield", title: "Protects Your Home", desc: "High-quality paints & coatings protect against harsh weather.", checklist: ["UV & fade resistant", "Moisture & mold resistant", "Peeling & cracking protection", "Built to withstand the NW climate"], image: img("1605276374104-dee2a0ed3cd6") },
    { icon: "dollar", title: "Long-Lasting Value", desc: "A professional paint job increases value and reduces maintenance.", checklist: ["Boosts property value", "Less maintenance long-term", "Durable premium coatings", "Excellent return on investment"], image: img("1564013799919-ab600027ffc6") },
    { icon: "badge", title: "Expert Craftsmanship", desc: "Attention to detail from prep to final walk-through.", checklist: ["Licensed & insured", "Experienced local crews", "On-time & on-budget", "100% satisfaction guarantee"], image: img("1583608205776-bfd35f0d9f83") },
  ],
  typesHeading: "Our Exterior Painting Services",
  types: [
    { title: "Full Exterior Painting", desc: "Complete repaint of siding, trim, doors, soffits, fascia & more.", checklist: ["Siding, trim & accents", "Doors, windows & shutters", "Fascia, soffits & eaves", "Garages & outbuildings"], image: img("1605146769289-440113cc3d00") },
    { title: "Siding Painting", desc: "Protect & refresh all types of siding materials.", checklist: ["Lap siding", "Fiber cement", "Wood & engineered wood", "Stucco & more"], image: img("1564013799919-ab600027ffc6") },
    { title: "Trim & Detail Painting", desc: "Crisp lines and perfect finishes on all the details.", checklist: ["Window & door trim", "Columns & railings", "Gutters & downspouts", "Decorative elements"], image: img("1605276374104-dee2a0ed3cd6") },
    { title: "Deck & Fence Staining", desc: "Beautiful, durable finishes that protect wood surfaces.", checklist: ["Deck staining & sealing", "Fence staining", "Pergolas & arbors", "Wood preservation"], image: img("1572120360610-d971b9d7767c") },
    { title: "Surface Preparation", desc: "Proper prep is the key to a long-lasting paint job.", checklist: ["Power washing", "Sanding & scraping", "Caulking & repairs", "Priming & sealing"], image: img("1583608205776-bfd35f0d9f83") },
  ],
  colorsHeading: "Popular Exterior Color Collections",
  colors: [
    { name: "Classic White", hex: "#f2f2ee" },
    { name: "Grey Mist", hex: "#b8bbbd" },
    { name: "Navy Blue", hex: "#24314a" },
    { name: "Forest Green", hex: "#2f4a38" },
    { name: "Warm Taupe", hex: "#a89478" },
    { name: "Sandstone", hex: "#cbb591" },
    { name: "Charcoal", hex: "#3a3d40" },
  ],
  comparison: {
    title: "Exterior Painting vs. DIY",
    columns: ["Professional Painting", "DIY Painting"],
    rows: [
      { icon: "wrench", feature: "Surface Preparation", values: ["Thorough & Proper", "Often Skipped or Rushed"] },
      { icon: "star", feature: "Paint Quality", values: ["Premium, Long-Lasting", "Lower Quality"] },
      { icon: "layers", feature: "Equipment", values: ["Professional Tools", "Basic Tools"] },
      { icon: "badge", feature: "Finish Quality", values: ["Smooth, Even Finish", "Streaks & Uneven"] },
      { icon: "clock", feature: "Time & Convenience", values: ["Fast & Hassle-Free", "Time-Consuming"] },
      { icon: "shield", feature: "Durability", values: ["5–10+ Years", "1–3 Years"] },
      { icon: "dollar", feature: "Warranty", values: ["Yes", "No"] },
    ],
  },
  processTitle: "Our Exterior Painting Process",
  processIntro: "",
  process: [
    { n: 1, icon: "search", title: "Consultation", desc: "We discuss your goals, inspect your home, and recommend the best solution." },
    { n: 2, icon: "star", title: "Color Selection", desc: "We help you choose the perfect colors and finishes." },
    { n: 3, icon: "wrench", title: "Prep Work", desc: "We clean, repair, caulk, sand, and prime all surfaces." },
    { n: 4, icon: "shield", title: "Protection", desc: "We protect your landscaping, windows, and walkways." },
    { n: 5, icon: "brush", title: "Premium Painting", desc: "We apply premium paints with expert techniques." },
    { n: 6, icon: "badge", title: "Final Inspection", desc: "We walk through together to ensure perfection." },
    { n: 7, icon: "trash", title: "Clean Up", desc: "We leave your home clean and beautiful, ready to enjoy." },
  ],
  processImage: img("1605146769289-440113cc3d00"),
  processTagline: "Detail. Protection. Beauty That Lasts.",
  standBehind: {
    title: "We Stand Behind Our Work",
    text: "All exterior painting projects include a workmanship warranty and use premium materials for lasting protection.",
    badge: "Satisfaction Guaranteed",
  },
  warranty: {
    title: "",
    text: "",
    tiers: [],
  },
  projectsHeading: "Recent Painting Projects",
  projects: [img("1605146769289-440113cc3d00"), img("1605276374104-dee2a0ed3cd6"), img("1564013799919-ab600027ffc6")],
  review: {
    name: "Jessica R.",
    city: "Kirkland, WA",
    initials: "JR",
    quote: "Skyve did an amazing job on the exterior of our home. The team was professional, careful, and the results are stunning!",
  },
  ctaTitle: "Ready For A Fresh New Look?",
  ctaSubtitle: "Boost your home's beauty and protect your investment with professional exterior painting by Skyve.",
  ctaTrust: [
    { icon: "badge", label: "No Obligation Estimate" },
    { icon: "zap", label: "Fast & Easy Process" },
    { icon: "shield", label: "Licensed & Insured" },
    { icon: "mappin", label: "Local Painting Experts" },
  ],
};
