/* AUTO-GENERATED by scripts/build-sitemap.mjs — do not edit by hand. */
export type SiteRoute = { path: string; photos: number; dynamic: boolean };
export const SITE_ROUTES: SiteRoute[] = [
  {
    "path": "/",
    "photos": 4,
    "dynamic": false
  },
  {
    "path": "/about",
    "photos": 1,
    "dynamic": false
  },
  {
    "path": "/all-pages",
    "photos": 0,
    "dynamic": false
  },
  {
    "path": "/ambassadors-program",
    "photos": 0,
    "dynamic": false
  },
  {
    "path": "/apply-partner",
    "photos": 2,
    "dynamic": false
  },
  {
    "path": "/calculators/financing",
    "photos": 1,
    "dynamic": false
  },
  {
    "path": "/calculators/material-comparison",
    "photos": 3,
    "dynamic": false
  },
  {
    "path": "/calculators/roof-cost",
    "photos": 3,
    "dynamic": true
  },
  {
    "path": "/calculators/roof-life-expectancy",
    "photos": 2,
    "dynamic": false
  },
  {
    "path": "/calculators/roof-replacement",
    "photos": 3,
    "dynamic": true
  },
  {
    "path": "/careers",
    "photos": 1,
    "dynamic": false
  },
  {
    "path": "/certifications",
    "photos": 2,
    "dynamic": false
  },
  {
    "path": "/contact",
    "photos": 3,
    "dynamic": false
  },
  {
    "path": "/contractors-program",
    "photos": 3,
    "dynamic": false
  },
  {
    "path": "/estimate",
    "photos": 0,
    "dynamic": false
  },
  {
    "path": "/estimate/detailed",
    "photos": 2,
    "dynamic": false
  },
  {
    "path": "/instant-estimate",
    "photos": 1,
    "dynamic": false
  },
  {
    "path": "/exteriors/deck-construction",
    "photos": 3,
    "dynamic": false
  },
  {
    "path": "/exteriors/deck-replacement",
    "photos": 3,
    "dynamic": false
  },
  {
    "path": "/exteriors/exterior-painting",
    "photos": 3,
    "dynamic": false
  },
  {
    "path": "/exteriors/fiber-cement-siding",
    "photos": 3,
    "dynamic": false
  },
  {
    "path": "/exteriors/gutter-guards",
    "photos": 4,
    "dynamic": false
  },
  {
    "path": "/exteriors/gutter-installation",
    "photos": 3,
    "dynamic": false
  },
  {
    "path": "/exteriors/gutter-replacement",
    "photos": 4,
    "dynamic": false
  },
  {
    "path": "/exteriors/siding-replacement",
    "photos": 3,
    "dynamic": false
  },
  {
    "path": "/exteriors/skylight-installation",
    "photos": 5,
    "dynamic": false
  },
  {
    "path": "/exteriors/skylight-replacement",
    "photos": 4,
    "dynamic": false
  },
  {
    "path": "/faq",
    "photos": 1,
    "dynamic": false
  },
  {
    "path": "/field-reports",
    "photos": 1,
    "dynamic": false
  },
  {
    "path": "/field-reports/1234-evergreen-lane",
    "photos": 4,
    "dynamic": true
  },
  {
    "path": "/financing",
    "photos": 0,
    "dynamic": false
  },
  {
    "path": "/investors-program",
    "photos": 2,
    "dynamic": false
  },
  {
    "path": "/learn",
    "photos": 6,
    "dynamic": false
  },
  {
    "path": "/learn/homeowner",
    "photos": 2,
    "dynamic": true
  },
  {
    "path": "/learn/metal-roofing",
    "photos": 2,
    "dynamic": true
  },
  {
    "path": "/learn/roof-repair",
    "photos": 2,
    "dynamic": true
  },
  {
    "path": "/learn/roof-replacement",
    "photos": 2,
    "dynamic": true
  },
  {
    "path": "/learn/shingles",
    "photos": 2,
    "dynamic": true
  },
  {
    "path": "/learn/skylights",
    "photos": 2,
    "dynamic": true
  },
  {
    "path": "/learn/storm-damage",
    "photos": 2,
    "dynamic": true
  },
  {
    "path": "/legal/ftc-disclosure",
    "photos": 3,
    "dynamic": false
  },
  {
    "path": "/legal/privacy",
    "photos": 1,
    "dynamic": false
  },
  {
    "path": "/legal/release-forms",
    "photos": 2,
    "dynamic": false
  },
  {
    "path": "/legal/revoke-consent",
    "photos": 2,
    "dynamic": false
  },
  {
    "path": "/legal/terms",
    "photos": 1,
    "dynamic": false
  },
  {
    "path": "/licenses-insurance",
    "photos": 2,
    "dynamic": false
  },
  {
    "path": "/login",
    "photos": 1,
    "dynamic": false
  },
  {
    "path": "/materials/architectural-shingles",
    "photos": 3,
    "dynamic": false
  },
  {
    "path": "/materials/cedar-shake-roofing",
    "photos": 3,
    "dynamic": false
  },
  {
    "path": "/materials/low-slope-roofing",
    "photos": 3,
    "dynamic": false
  },
  {
    "path": "/materials/luxury-shingles",
    "photos": 3,
    "dynamic": false
  },
  {
    "path": "/materials/metal-roofing",
    "photos": 3,
    "dynamic": false
  },
  {
    "path": "/materials/pvc-roofing",
    "photos": 3,
    "dynamic": false
  },
  {
    "path": "/materials/standing-seam-roofing",
    "photos": 3,
    "dynamic": false
  },
  {
    "path": "/materials/synthetic-shake-roofing",
    "photos": 3,
    "dynamic": false
  },
  {
    "path": "/materials/tpo-roofing",
    "photos": 3,
    "dynamic": false
  },
  {
    "path": "/portal",
    "photos": 4,
    "dynamic": false
  },
  {
    "path": "/portal/budget-payments",
    "photos": 2,
    "dynamic": false
  },
  {
    "path": "/portal/change-orders",
    "photos": 2,
    "dynamic": false
  },
  {
    "path": "/portal/documents",
    "photos": 2,
    "dynamic": false
  },
  {
    "path": "/portal/help-support",
    "photos": 2,
    "dynamic": false
  },
  {
    "path": "/portal/inspection-history",
    "photos": 3,
    "dynamic": false
  },
  {
    "path": "/portal/maintenance",
    "photos": 4,
    "dynamic": false
  },
  {
    "path": "/portal/messages",
    "photos": 5,
    "dynamic": false
  },
  {
    "path": "/portal/monitoring",
    "photos": 2,
    "dynamic": false
  },
  {
    "path": "/portal/my-home",
    "photos": 4,
    "dynamic": false
  },
  {
    "path": "/portal/my-profile",
    "photos": 2,
    "dynamic": false
  },
  {
    "path": "/portal/photos",
    "photos": 3,
    "dynamic": false
  },
  {
    "path": "/portal/project-timeline",
    "photos": 3,
    "dynamic": false
  },
  {
    "path": "/portal/property-passport",
    "photos": 3,
    "dynamic": false
  },
  {
    "path": "/portal/resources",
    "photos": 4,
    "dynamic": false
  },
  {
    "path": "/portal/roof-score",
    "photos": 3,
    "dynamic": false
  },
  {
    "path": "/portal/selections",
    "photos": 4,
    "dynamic": false
  },
  {
    "path": "/portal/settings",
    "photos": 2,
    "dynamic": false
  },
  {
    "path": "/portal/timeline",
    "photos": 2,
    "dynamic": false
  },
  {
    "path": "/portal/warranty",
    "photos": 2,
    "dynamic": false
  },
  {
    "path": "/pro-partner",
    "photos": 3,
    "dynamic": false
  },
  {
    "path": "/projects",
    "photos": 4,
    "dynamic": false
  },
  {
    "path": "/realtors-program",
    "photos": 3,
    "dynamic": false
  },
  {
    "path": "/reviews",
    "photos": 1,
    "dynamic": false
  },
  {
    "path": "/reviews/complete-roof-replacement",
    "photos": 4,
    "dynamic": true
  },
  {
    "path": "/roofing-arlington-wa",
    "photos": 3,
    "dynamic": false
  },
  {
    "path": "/roofing-auburn-wa",
    "photos": 3,
    "dynamic": false
  },
  {
    "path": "/roofing-bellevue-wa",
    "photos": 3,
    "dynamic": false
  },
  {
    "path": "/roofing-bothell-wa",
    "photos": 3,
    "dynamic": false
  },
  {
    "path": "/roofing-brier-wa",
    "photos": 3,
    "dynamic": false
  },
  {
    "path": "/roofing-burien-wa",
    "photos": 3,
    "dynamic": false
  },
  {
    "path": "/roofing-edmonds-wa",
    "photos": 3,
    "dynamic": false
  },
  {
    "path": "/roofing-everett-wa",
    "photos": 3,
    "dynamic": false
  },
  {
    "path": "/roofing-federal-way-wa",
    "photos": 3,
    "dynamic": false
  },
  {
    "path": "/roofing-issaquah-wa",
    "photos": 3,
    "dynamic": false
  },
  {
    "path": "/roofing-kenmore-wa",
    "photos": 3,
    "dynamic": false
  },
  {
    "path": "/roofing-kent-wa",
    "photos": 3,
    "dynamic": false
  },
  {
    "path": "/roofing-kirkland-wa",
    "photos": 3,
    "dynamic": false
  },
  {
    "path": "/roofing-lake-stevens-wa",
    "photos": 3,
    "dynamic": false
  },
  {
    "path": "/roofing-lynnwood-wa",
    "photos": 3,
    "dynamic": false
  },
  {
    "path": "/roofing-marysville-wa",
    "photos": 3,
    "dynamic": false
  },
  {
    "path": "/roofing-mercer-island-wa",
    "photos": 3,
    "dynamic": false
  },
  {
    "path": "/roofing-mill-creek-wa",
    "photos": 3,
    "dynamic": false
  },
  {
    "path": "/roofing-monroe-wa",
    "photos": 3,
    "dynamic": false
  },
  {
    "path": "/roofing-mountlake-terrace-wa",
    "photos": 3,
    "dynamic": false
  },
  {
    "path": "/roofing-mukilteo-wa",
    "photos": 3,
    "dynamic": false
  },
  {
    "path": "/roofing-newcastle-wa",
    "photos": 3,
    "dynamic": false
  },
  {
    "path": "/roofing-redmond-wa",
    "photos": 3,
    "dynamic": false
  },
  {
    "path": "/roofing-renton-wa",
    "photos": 3,
    "dynamic": false
  },
  {
    "path": "/roofing-sammamish-wa",
    "photos": 3,
    "dynamic": false
  },
  {
    "path": "/roofing-seatac-wa",
    "photos": 3,
    "dynamic": false
  },
  {
    "path": "/roofing-seattle-wa",
    "photos": 3,
    "dynamic": false
  },
  {
    "path": "/roofing-shoreline-wa",
    "photos": 3,
    "dynamic": false
  },
  {
    "path": "/roofing-snohomish-wa",
    "photos": 3,
    "dynamic": false
  },
  {
    "path": "/roofing-stanwood-wa",
    "photos": 3,
    "dynamic": false
  },
  {
    "path": "/roofing-tukwila-wa",
    "photos": 3,
    "dynamic": false
  },
  {
    "path": "/roofing-woodinville-wa",
    "photos": 3,
    "dynamic": false
  },
  {
    "path": "/safety-program",
    "photos": 3,
    "dynamic": false
  },
  {
    "path": "/service-area",
    "photos": 2,
    "dynamic": false
  },
  {
    "path": "/services",
    "photos": 1,
    "dynamic": false
  },
  {
    "path": "/services/emergency-roof-repair",
    "photos": 1,
    "dynamic": false
  },
  {
    "path": "/services/insurance-claims-assistance",
    "photos": 3,
    "dynamic": false
  },
  {
    "path": "/services/roof-certifications",
    "photos": 1,
    "dynamic": false
  },
  {
    "path": "/services/roof-cleaning",
    "photos": 5,
    "dynamic": false
  },
  {
    "path": "/services/roof-inspection",
    "photos": 1,
    "dynamic": false
  },
  {
    "path": "/services/roof-leak-repair",
    "photos": 4,
    "dynamic": false
  },
  {
    "path": "/services/roof-maintenance",
    "photos": 5,
    "dynamic": false
  },
  {
    "path": "/services/roof-repair",
    "photos": 2,
    "dynamic": false
  },
  {
    "path": "/services/roof-replacement",
    "photos": 4,
    "dynamic": false
  },
  {
    "path": "/services/roof-ventilation",
    "photos": 6,
    "dynamic": false
  },
  {
    "path": "/services/storm-damage-repair",
    "photos": 4,
    "dynamic": false
  },
  {
    "path": "/share-your-story",
    "photos": 0,
    "dynamic": false
  },
  {
    "path": "/skyve-tv",
    "photos": 2,
    "dynamic": false
  },
  {
    "path": "/skyve-tv/roof-replacement",
    "photos": 1,
    "dynamic": true
  },
  {
    "path": "/testimonials",
    "photos": 2,
    "dynamic": false
  },
  {
    "path": "/warranty",
    "photos": 3,
    "dynamic": false
  },
  {
    "path": "/warranty/register",
    "photos": 1,
    "dynamic": false
  },
  {
    "path": "/warranty/register/type",
    "photos": 1,
    "dynamic": false
  },
  {
    "path": "/why-skyve",
    "photos": 0,
    "dynamic": false
  }
];
export const SITE_TOTAL_PHOTOS = 354;
