// Builds a site map: every route + how many image slots (<Photo>) it renders.
// Walks the local import graph from each page.tsx under app.
// Outputs lib/site-map.ts (typed data for /all-pages) and SITEMAP.md.

import { readFileSync, writeFileSync, readdirSync, statSync, existsSync } from "node:fs";
import { join, dirname, resolve } from "node:path";

const ROOT = resolve(".");

function walk(dir, out = []) {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    const st = statSync(p);
    if (st.isDirectory()) walk(p, out);
    else out.push(p);
  }
  return out;
}

/* resolve an import specifier from a file to an on-disk path */
function resolveImport(spec, fromFile) {
  let base;
  if (spec.startsWith("@/")) base = join(ROOT, spec.slice(2));
  else if (spec.startsWith("./") || spec.startsWith("../")) base = resolve(dirname(fromFile), spec);
  else return null; // package import — skip
  for (const ext of [".tsx", ".ts", "/index.tsx", "/index.ts"]) {
    if (existsSync(base + ext)) return base + ext;
  }
  if (existsSync(base)) return base;
  return null;
}

const importRe = /import[^"']*["']([^"']+)["']/g;

/* collect all local files reachable from an entry, count <Photo occurrences */
function analyze(entry) {
  const seen = new Set();
  const stack = [entry];
  let photos = 0;
  while (stack.length) {
    const f = stack.pop();
    if (seen.has(f)) continue;
    seen.add(f);
    let src;
    try { src = readFileSync(f, "utf8"); } catch { continue; }
    photos += (src.match(/<Photo\b/g) || []).length;
    let m;
    importRe.lastIndex = 0;
    while ((m = importRe.exec(src))) {
      const r = resolveImport(m[1], f);
      if (r && !seen.has(r)) stack.push(r);
    }
  }
  return photos;
}

/* dynamic slug expansions so every real page is listed */
const EXPAND = {
  "/learn/[category]": ["roof-replacement", "roof-repair", "shingles", "metal-roofing", "skylights", "storm-damage", "homeowner"],
  "/calculators/[calc]": ["roof-cost", "roof-replacement"],
  "/field-reports/[slug]": ["1234-evergreen-lane"],
  "/reviews/[slug]": ["complete-roof-replacement"],
  "/skyve-tv/[category]": ["roof-replacement"],
};

const pages = walk(join(ROOT, "app")).filter((p) => p.endsWith("page.tsx"));

const routes = [];
for (const file of pages) {
  let route = file.slice(join(ROOT, "app").length).replace(/\\/g, "/").replace(/\/page\.tsx$/, "") || "/";
  const photos = analyze(file);
  const dynSeg = route.match(/\[[^\]]+\]/);
  if (dynSeg) {
    const key = route;
    const slugs = EXPAND[key] || ["sample"];
    for (const s of slugs) routes.push({ path: route.replace(/\[[^\]]+\]/, s), photos, dynamic: true });
  } else {
    routes.push({ path: route, photos, dynamic: false });
  }
}

routes.sort((a, b) => a.path.localeCompare(b.path));

const totalPhotos = routes.reduce((n, r) => n + r.photos, 0);

/* write typed data for the hub */
const ts = `/* AUTO-GENERATED by scripts/build-sitemap.mjs — do not edit by hand. */
export type SiteRoute = { path: string; photos: number; dynamic: boolean };
export const SITE_ROUTES: SiteRoute[] = ${JSON.stringify(routes, null, 2)};
export const SITE_TOTAL_PHOTOS = ${totalPhotos};
`;
writeFileSync(join(ROOT, "lib/site-map.ts"), ts);

/* write SITEMAP.md */
let md = `# Skyve Roofing — Site Map\n\n${routes.length} routes · ${totalPhotos} image slots (\`<Photo>\`) total.\n\n`;
md += `> Regenerate with: \`node scripts/build-sitemap.mjs\`\n\n`;
md += `| # | Path | Images |\n|---|------|:------:|\n`;
routes.forEach((r, i) => {
  md += `| ${i + 1} | \`${r.path}\` | ${r.photos || "—"} |\n`;
});
writeFileSync(join(ROOT, "SITEMAP.md"), md);

console.log(`Wrote lib/site-map.ts and SITEMAP.md — ${routes.length} routes, ${totalPhotos} image slots.`);
